import type { WorksheetSet } from "@/lib/worksheets";

/** Adding and taking away: the sheets are in teaching order, easiest first. Add new ones where they belong in that order. */
export const addingAndTakingAway: WorksheetSet = {
  slug: "adding-and-taking-away",
  title: "Adding and taking away",
  subject: "Maths",
  summary: "Number bonds, then adding and taking away with bigger numbers.",
  sheets: [
    {
      slug: "number-bonds-to-10",
      title: "Number bonds to 10",
      subject: "Maths",
      topic: "Pairs of numbers that make 10",
      ages: "5 to 7",
      color: "#E8573C",
      intro: "Two numbers that add up to 10 are called a number bond. Find the partner for each number.",
      cover: { kind: "tenframe", filled: 7 },
      comic: "captain-ten",
      questions: [
        {
          type: "choice",
          q: "There are 7 counters in the ten frame. How many more make 10?",
          visual: { kind: "tenframe", filled: 7 },
          options: ["2", "3", "4"],
          answer: 1,
          why: "There are 3 empty boxes. 7 and 3 make 10.",
        },
        { type: "type", q: "4 + ? = 10. What is the missing number?", answer: "6", why: "4 and 6 make 10." },
        { type: "type", q: "10 take away 8 is…", answer: "2", why: "8 and 2 make 10, so 10 take away 8 leaves 2." },
        {
          type: "match",
          q: "Match the partners that make 10.",
          pairs: [["1", "9"], ["2", "8"], ["3", "7"], ["5", "5"]],
        },
        {
          type: "gap",
          q: "Fill the gaps.",
          text: "6 + ___ = 10  and  0 + ___ = 10",
          bank: ["4", "5", "6", "10"],
          answers: ["4", "10"],
        },
        {
          type: "choice",
          q: "Half of the ten frame is full. Which sum does it show?",
          visual: { kind: "tenframe", filled: 5 },
          options: ["5 + 5 = 10", "4 + 6 = 10", "5 + 4 = 10"],
          answer: 0,
          why: "5 boxes are full and 5 are empty.",
        },
        { type: "type", q: "Captain Ten has 10 planks. He uses 1. How many are left?", answer: "9", why: "1 and 9 make 10." },
        {
          type: "choice",
          q: "Which pair does not make 10?",
          options: ["7 and 3", "6 and 5", "8 and 2"],
          answer: 1,
          why: "6 and 5 make 11. The partner for 6 is 4.",
        },
        { type: "type", q: "3 + 7 = ?", answer: "10" },
        {
          type: "type",
          q: "Milo has 10p. A sticker costs 6p. How much change does he get?",
          answer: "4",
          after: "p",
          why: "6 and 4 make 10, so he gets 4p back.",
        },
      ],
    },
    {
      slug: "adding-and-taking-away-to-20",
      title: "Adding and taking away to 20",
      subject: "Maths",
      topic: "Addition and subtraction within 20",
      ages: "5 to 7",
      color: "#3F7FBF",
      intro: "Use the number line to jump forwards when you add and backwards when you take away.",
      cover: { kind: "numberline", from: 0, to: 20, jump: [8, 13] },
      questions: [
        {
          type: "type",
          q: "Start at 8 and jump on 5. Where do you land?",
          visual: { kind: "numberline", from: 0, to: 20, jump: [8, 13] },
          answer: "13",
        },
        { type: "type", q: "9 + 6 = ?", answer: "15", why: "9 and 1 make 10, then 5 more makes 15." },
        {
          type: "type",
          q: "14 take away 5 is…",
          visual: { kind: "numberline", from: 0, to: 20, jump: [14, 9] },
          answer: "9",
        },
        { type: "choice", q: "Which sum makes 12?", options: ["7 + 5", "6 + 5", "8 + 3"], answer: 0, why: "6 + 5 and 8 + 3 both make 11." },
        { type: "gap", q: "Fill the gap.", text: "7 + ___ = 15", bank: ["6", "7", "8", "9"], answers: ["8"] },
        {
          type: "match",
          q: "Match each double to its answer.",
          pairs: [["6 + 6", "12"], ["7 + 7", "14"], ["8 + 8", "16"], ["9 + 9", "18"]],
        },
        { type: "type", q: "There are 17 birds on a fence. 4 fly away. How many are left?", answer: "13" },
        { type: "choice", q: "20 − 7 = ?", options: ["12", "13", "14"], answer: 1 },
        { type: "type", q: "Sam has 8 red cars and 7 blue cars. How many cars altogether?", answer: "15" },
        {
          type: "order",
          q: "Work out each sum, then tap them from the smallest answer to the largest.",
          items: ["5 + 4", "6 + 6", "20 − 3", "10 + 10"],
          why: "The answers are 9, 12, 17 and 20.",
        },
      ],
    },
  ],
};
