"""Life skills for ages 11 to 16: the everyday jobs that school rarely teaches. Written for Bright Roots.

Steps are written for the teenager to do themselves. "Grown-up" marks are kept for jobs where a
check from an adult matters for safety, such as anything electrical.
"""
from make_starters import G, _item

HOME = "Around the home"
CLOTHES = "Clothes care"
MONEY = "Money and admin"
OUT = "Out and about"
SAFE = "Staying safe"

LIFE_SKILLS = [
    _item(
        "life", "life-washing-machine", "Use a washing machine", "🧺", CLOTHES, 30, "easy", 11, None,
        "Sort, wash and dry a load of your own clothes from start to finish.",
        [("", "a load of washing"), ("", "detergent"), ("", "a washing machine"), ("", "an airer, washing line or tumble dryer")],
        ["Check the care label inside each item. The number in the wash tub symbol is the hottest temperature it can take.",
         "Sort into piles: whites, darks and colours. Wash anything new and brightly coloured on its own the first time.",
         "Empty every pocket, zip up zips and turn jeans and printed tops inside out.",
         "Load the drum loosely. You should be able to fit your hand flat above the washing.",
         "Add detergent: liquid or powder goes in the drawer section marked II, pods go in the drum before the clothes.",
         "Choose a programme. 30 or 40 degrees on a cotton or mixed cycle suits most everyday clothes.",
         "When it finishes, take the washing out straight away so it doesn't smell or crease.",
         "Shake each item out and hang it to dry, or tumble dry only what the label says is safe."],
        "Towels and bedding wash best at 60 degrees. Wool and anything delicate needs its own gentle cycle.",
    ),
    _item(
        "life", "life-wire-a-plug", "Wire a UK plug", "🔌", HOME, 30, "tricky", 12, None,
        "Learn what the three wires do and how to fit a plug safely. A classic skill that is still worth knowing.",
        [("1", "three-pin plug"), ("1", "length of three-core flex that is NOT connected to anything"), ("1", "small screwdriver"), ("1", "wire strippers")],
        [("Do this only with a practice flex that isn't attached to an appliance or plugged in anywhere.", G),
         "Unscrew the big screw on the back of the plug and take the cover off.",
         "Learn the three wires: brown is live, blue is neutral, green and yellow is earth.",
         "Strip about 5 mm of plastic from the end of each wire and twist the copper strands together.",
         "Blue goes to the left terminal (N). Think: bLue, Left.",
         "Brown goes to the right terminal (L), next to the fuse. Think: bRown, Right.",
         "Green and yellow goes to the top terminal (E).",
         "Tighten each screw so no bare copper shows and no stray strands stick out.",
         "Clamp the cord grip over the outer cable, not over the three thin wires.",
         "Check the fuse: 3 amp for appliances up to 700 watts, 13 amp for anything more powerful. Screw the cover back on.",
         ("A grown-up must check the finished plug before it is ever used.", G)],
        "Most new appliances come with a sealed plug, so the job you'll do most often is changing the fuse.",
    ),
    _item(
        "life", "life-iron-a-shirt", "Iron a shirt", "👔", CLOTHES, 20, "medium", 12, None,
        "Get a shirt properly smooth in the right order, without scorching it or yourself.",
        [("1", "shirt, slightly damp if possible"), ("1", "iron"), ("1", "ironing board")],
        ["Check the care label: one dot means a cool iron, two dots warm, three dots hot.",
         ("Set up the board near a socket, fill the iron with water if it's a steam iron, and switch it on.", G),
         "Start with the collar: iron the underside first, from the points towards the middle.",
         "Do the cuffs, then lay each sleeve flat and iron from the shoulder down.",
         "Iron the two front panels, working carefully around the buttons.",
         "Finish with the back, then hang the shirt on a hanger straight away.",
         "Always stand the iron upright on its heel when you put it down, never flat.",
         "Switch off and unplug it, and leave it somewhere safe to cool."],
        "Never leave a hot iron unattended, and keep the flex where nobody can trip over it.",
    ),
    _item(
        "life", "life-sew-a-button", "Sew on a button", "🪡", CLOTHES, 15, "easy", 11, None,
        "Fix a missing button so it stays on. Five minutes that saves a favourite shirt.",
        [("1", "button"), ("1", "needle"), ("", "thread that matches"), ("", "scissors")],
        ["Cut a piece of thread about as long as your arm, thread the needle and knot the two ends together.",
         "Push the needle up from the back of the fabric where the button should sit.",
         "Thread on the button and go down through the opposite hole.",
         "Repeat five or six times. On a four-hole button, make two parallel lines or a cross.",
         "Bring the needle up under the button, not through a hole, and wind the thread round the stitches three times.",
         "Push the needle to the back and make three small stitches on top of each other to finish.",
         "Snip the thread close to the fabric."],
        "Lay a matchstick or pin across the button while you sew. It leaves just enough slack for the buttonhole.",
    ),
    _item(
        "life", "life-change-a-bed", "Change your bedding", "🛏️", HOME, 20, "easy", 11, None,
        "Strip the bed, put on fresh sheets and beat the duvet cover without getting stuck inside it.",
        [("1", "clean fitted sheet"), ("1", "clean duvet cover"), ("", "clean pillowcases")],
        ["Strip everything off the bed and put it straight in the wash basket.",
         "Fit the sheet one corner at a time, doing opposite corners so it doesn't ping off.",
         "Turn the clean duvet cover inside out and lay it flat on the bed.",
         "Put your hands inside and grab the two far corners of the cover through the fabric.",
         "Still holding them, grab the two top corners of the duvet and shake the cover down over it.",
         "Do up the buttons or poppers and give it a good shake to settle the duvet into the corners.",
         "Put the pillowcases on and make the bed."],
        "Bedding should be washed about once a week or fortnight, at 60 degrees if the label allows.",
    ),
    _item(
        "life", "life-clean-a-bathroom", "Clean a bathroom properly", "🧽", HOME, 30, "medium", 11, None,
        "Clean a bathroom in a sensible order so you only do each bit once.",
        [("", "bathroom cleaner"), ("", "toilet cleaner and brush"), ("2", "cloths: one for the toilet only"), ("", "rubber gloves"), ("", "glass cloth or newspaper")],
        ["Open the window or switch on the fan, and put on your gloves.",
         "Squirt toilet cleaner under the rim and leave it to work while you do everything else.",
         "Clear the surfaces, then spray the sink, bath and shower and leave for a minute.",
         "Work from the top down: mirror first, then shelves, sink, bath and shower. Rinse as you go.",
         "Scrub the toilet bowl with the brush and flush. Wipe the seat, lid and outside with the toilet-only cloth.",
         "Empty the bin and put out a clean towel.",
         "Sweep or vacuum the floor, then mop from the far corner back to the door."],
        "Never mix bleach with any other cleaning product. Together they can give off dangerous fumes.",
    ),
    _item(
        "life", "life-home-emergencies", "Know your home's off switches", "🏠", SAFE, 30, "medium", 11, None,
        "Find the stopcock, the fuse box and the smoke alarms before you ever need them in a hurry.",
        [("", "a torch"), ("", "paper and a pen for a home safety map")],
        [("Walk round the house together to find each of these.", G),
         "Find the stopcock, which turns off the water. It is often under the kitchen sink. Turn it clockwise to close.",
         "Find the consumer unit (fuse box). See how a tripped switch sits in the down position and how to push it back up.",
         "Never touch the fuse box with wet hands, and tell a grown-up if a switch keeps tripping.",
         "Press the test button on each smoke alarm until it beeps. Do this once a month.",
         "Learn the gas rule: if you smell gas, don't touch any switches, open the windows, go outside and call 0800 111 999.",
         "Draw a simple map of your home showing where everything is, and stick it inside a cupboard door."],
        "A burst pipe does far less damage if someone can turn the water off in the first minute.",
    ),
    _item(
        "life", "life-first-aid", "First aid basics", "🩹", SAFE, 45, "medium", 11, None,
        "What to do for cuts, burns and someone who has collapsed, and how to call for help.",
        [("", "a first aid kit"), ("", "a willing volunteer to practise on")],
        ["Cuts: wash your hands, rinse the cut under running water, press on it with a clean pad until the bleeding stops, then cover it.",
         "Burns: hold the burn under cool running water for 20 minutes. Take off rings or watches nearby. Never use ice, butter or creams.",
         "After cooling, cover a burn loosely with cling film or a clean plastic bag.",
         "Practise the recovery position on your volunteer: on their side, top knee bent, head tilted back so the airway stays open.",
         "Learn when to call 999: someone is unconscious, not breathing normally, bleeding heavily, or badly burned.",
         "Practise what you'd say: where you are, what has happened, and how the person is now. Stay on the line.",
         ("Check the family first aid kit together and replace anything used or out of date.", G)],
        "St John Ambulance and the British Red Cross both run first aid courses for young people.",
    ),
    _item(
        "life", "life-first-budget", "Make your first budget", "💷", MONEY, 40, "medium", 12, None,
        "Work out what comes in, what goes out and how to save for something you want.",
        [("", "paper or a spreadsheet"), ("", "a record of your pocket money, allowance or earnings")],
        ["Write down everything that comes in each month: pocket money, allowance, any earnings.",
         "Keep a note of everything you spend for two weeks, however small.",
         "Sort your spending into needs, wants and savings.",
         "Choose a savings goal and work out how many weeks it will take at different amounts.",
         "Set a budget for next month: an amount for each group that adds up to no more than what comes in.",
         "At the end of the month, compare what you planned with what really happened and adjust."],
        "A simple rule to start with: save some as soon as money arrives, and spend what's left.",
    ),
    _item(
        "life", "life-formal-email", "Write a formal email", "✉️", MONEY, 25, "easy", 12, None,
        "Write a clear, polite email to someone you don't know, such as a club, a college or an employer.",
        [("", "a device with email"), ("", "a real or made-up reason to write")],
        ["Write a subject line that says exactly what the email is about.",
         "Open with 'Dear' and their name, or 'Dear Sir or Madam' if you don't know it.",
         "Say who you are and why you are writing in the first two sentences.",
         "Give the details they need, in short paragraphs. Ask one clear question or make one clear request.",
         "Finish with a thank you, then 'Yours sincerely' if you used their name or 'Yours faithfully' if you didn't.",
         "Read it out loud to check for mistakes, and check any attachment is actually attached.",
         ("Ask a grown-up to read it before you press send.", G)],
        "Keep your email address sensible. One with your name in it is taken more seriously than a jokey one.",
    ),
    _item(
        "life", "life-plan-a-journey", "Plan a journey by bus or train", "🚌", OUT, 45, "medium", 12, None,
        "Plan a trip on public transport, including times, tickets and what to do if something goes wrong.",
        [("", "a journey planner app or website, such as Traveline"), ("", "a timetable"), ("", "money or a travel card")],
        ["Pick a real destination and the time you need to arrive by.",
         "Use a journey planner to find routes, then check the times against the timetable yourself.",
         "Work backwards: what time must you leave home to catch it, allowing time to walk to the stop?",
         "Find out what ticket you need, what it costs and whether a young person's fare or railcard applies.",
         "Plan the way back, including the last service of the day.",
         "Decide what you'd do if you missed it or it was cancelled: the next service, and who you'd phone.",
         ("Do the journey together first, with you leading. Then agree when you're ready to do it alone.", G)],
        "Charge your phone before you go and take a note of the important times on paper too.",
    ),
    _item(
        "life", "life-fix-a-puncture", "Fix a bike puncture", "🚲", OUT, 40, "medium", 11, None,
        "Mend a flat tyre yourself instead of pushing the bike home.",
        [("1", "puncture repair kit"), ("2 or 3", "tyre levers"), ("1", "pump"), ("", "a bowl of water")],
        ["Turn the bike upside down or take the wheel off, and let out any air left in the tyre.",
         "Hook a tyre lever under the edge of the tyre and lever it over the rim. Work round with a second lever.",
         "Pull out the inner tube, pump a little air into it and hold it under water. Bubbles show the hole.",
         "Dry the tube, mark the hole and roughen the area around it with the sandpaper from the kit.",
         "Spread a thin layer of glue, wait until it's tacky, then press the patch on firmly for a minute.",
         "Run your fingers carefully round the inside of the tyre to find the thorn or glass that caused it.",
         "Tuck the tube back in, push the tyre back onto the rim with your thumbs, and pump it up."],
        "Carry a spare inner tube on longer rides. Swapping the tube is quicker than patching at the roadside.",
    ),
    _item(
        "life", "life-food-safety", "Food labels and fridge safety", "🥫", HOME, 30, "easy", 11, None,
        "Understand use-by dates, store food safely and read a label for allergens.",
        [("", "the fridge and food cupboard"), ("", "a few packets and tins to read")],
        ["Find a use-by date and a best-before date. Use-by is about safety: don't eat it after that day. Best-before is about quality.",
         "Check the fridge is at 5 degrees or below.",
         "Sort the fridge: raw meat and fish on the bottom shelf in sealed containers, ready-to-eat food above.",
         "Read an ingredients list. Allergens such as milk, egg, nuts and wheat are shown in bold.",
         "Compare two similar products using the per 100 g column for sugar and salt.",
         "Learn the leftovers rule: cool quickly, into the fridge within two hours, eat within two days, and reheat until steaming hot."],
        "Always wash your hands before cooking and after touching raw meat.",
    ),
]


READY = "Getting ready"
HELPING = "Helping at home"
KNOWHOW = "Everyday know-how"
SAFE_YOUNG = "Staying safe"

# Life skills for younger children (about 3 to 9): the first steps to doing things for themselves.
YOUNG_LIFE_SKILLS = [
    _item(
        "life", "life-young-shoelaces", "Tie your shoelaces", "👟", READY, 15, "medium", 5, None,
        "Learn the bunny ears way to tie a bow. It takes practice, so try a little every day.",
        [("1", "shoe with laces, on a table to start with")],
        ["Cross one lace over the other to make an X.",
         "Tuck the top lace under and through, and pull both ends tight.",
         "Make a loop with each lace. These are the bunny ears.",
         "Cross the bunny ears over each other to make another X.",
         "Tuck one ear under and through the gap, just like before.",
         "Pull both loops tight. You've tied a bow!",
         ("Practise together on a shoe on the table before trying it on a foot.", G)],
        "Two different coloured laces make it much easier to see which one goes where.",
    ),
    _item(
        "life", "life-young-make-bed", "Make your bed", "🛏️", HELPING, 5, "easy", 4, None,
        "A tidy bed in five easy steps. A great job to do every morning.",
        [("", "your bed")],
        ["Pull the bottom sheet smooth with flat hands.",
         "Plump your pillow by squashing it from both sides, and put it at the top.",
         "Pull the duvet or blanket right up to the pillow.",
         "Smooth out the lumps and bumps.",
         "Put your teddy or favourite toy on top to finish."],
        "It doesn't have to be perfect. Doing it yourself is what counts.",
    ),
    _item(
        "life", "life-young-get-dressed", "Buttons, zips and getting dressed", "🧥", READY, 15, "medium", 4, None,
        "Do up buttons, start a zip and get your coat on all by yourself.",
        [("1", "coat with a zip"), ("1", "shirt or cardigan with big buttons")],
        ["Lay tomorrow's clothes out in the order you put them on.",
         "Buttons: push the button halfway through the hole, then pull it out the other side. Start at the bottom so they line up.",
         "Zips: push the pin right down into the box at the bottom and hold the box still.",
         "Hold the bottom of the coat with one hand and pull the zip up with the other.",
         "Check your shoes are on the right feet: the curved sides should face each other.",
         ("Help with the first try, then step back and let them have a go.", G)],
        "Practise buttons on clothes laid on the table first. It's much easier than doing them on yourself.",
    ),
    _item(
        "life", "life-young-wash-hands", "Wash your hands properly", "🧼", READY, 5, "easy", 3, None,
        "Wash away the germs you can't see. It takes about as long as singing Happy Birthday twice.",
        [("", "soap"), ("", "warm water"), ("", "a clean towel")],
        ["Wet your hands with warm water.",
         "Rub in the soap to make lots of bubbles.",
         "Scrub your palms, the backs of your hands, and in between your fingers.",
         "Don't forget your thumbs and under your nails.",
         "Rinse all the bubbles away.",
         "Dry your hands well with a clean towel."],
        "Always wash your hands after the toilet, before eating and after playing outside.",
    ),
    _item(
        "life", "life-young-brush-teeth", "Brush your teeth", "🦷", READY, 5, "easy", 3, None,
        "Brush for two minutes, twice a day, and reach every tooth.",
        [("1", "toothbrush"), ("", "fluoride toothpaste"), ("", "a two-minute timer or song")],
        ["Squeeze a pea-sized blob of toothpaste onto your brush.",
         "Brush the outsides of your teeth with small circles, top and bottom.",
         "Brush the insides, tilting the brush for the front teeth.",
         "Brush the flat tops where you chew.",
         "Keep going until the two minutes are up.",
         "Spit out the toothpaste, but don't rinse with water.",
         ("Children usually need help or checking with brushing until about age 7.", G)],
        "Brush last thing at night and one other time in the day.",
    ),
    _item(
        "life", "life-young-set-table", "Set the table", "🍽️", HELPING, 10, "easy", 4, None,
        "Get the table ready for a family meal so everyone has what they need.",
        [("", "plates"), ("", "knives, forks and spoons"), ("", "cups"), ("", "mats or napkins")],
        ["Count how many people are eating.",
         "Put a mat or plate at each place.",
         "The fork goes on the left of the plate.",
         "The knife goes on the right, with the spoon next to it.",
         "Put a cup above the knife.",
         "Stand back and check every place has everything."],
        "A handy way to remember: fork and left both have four letters. Knife and right both have five.",
    ),
    _item(
        "life", "life-young-tell-time", "Tell the time", "🕒", KNOWHOW, 20, "medium", 6, None,
        "Read o'clock and half past on a clock with hands.",
        [("1", "clock with hands, or a paper plate clock you've made")],
        ["Find the short hand. It points to the hour.",
         "Find the long hand. It tells you the minutes.",
         "When the long hand points straight up at 12, it is something o'clock.",
         "When the long hand points straight down at 6, it is half past.",
         "Move the hands to show 3 o'clock, then half past 7.",
         ("Ask 'what time is it?' at breakfast, lunch and bedtime every day this week.", G)],
        "Make a paper plate clock with a split pin so the hands can turn.",
    ),
    _item(
        "life", "life-young-address-999", "Know your address and when to call 999", "☎️", SAFE_YOUNG, 20, "easy", 5, None,
        "Learn your full name, your address and how to get help in an emergency.",
        [("", "paper and pens"), ("", "a toy phone or a phone that is switched off")],
        ["Practise saying your full name and the name of your grown-up.",
         "Learn your address: the house number, the street and the town.",
         "Draw your house and write the address underneath.",
         "Talk about what an emergency is: someone is badly hurt, there's a fire, or a grown-up won't wake up.",
         "Practise on a pretend phone: press 9, 9, 9, and say what has happened and where you are.",
         ("Explain that 999 is only for real emergencies, and never for a game.", G)],
        "Stick your address somewhere easy to find, like on the fridge.",
    ),
    _item(
        "life", "life-young-cross-road", "Cross the road safely", "🚸", SAFE_YOUNG, 20, "easy", 5, None,
        "Learn the Green Cross Code and practise it together on a real walk.",
        [("", "a quiet road to practise on"), ("", "a grown-up to hold hands with")],
        ["Think: find a safe place to cross, like a crossing or where you can see clearly both ways.",
         "Stop: stand on the pavement, a little way back from the kerb.",
         "Look and listen: look right, look left, look right again, and listen for traffic.",
         "Wait: let any traffic pass. If you're not sure, don't cross.",
         "Walk straight across. Don't run.",
         "Keep looking and listening while you cross.",
         ("Always hold hands and cross together. Let them lead the steps out loud.", G)],
        "Never cross between parked cars if you can help it. Drivers can't see you.",
    ),
    _item(
        "life", "life-young-pack-bag", "Pack your own bag", "🎒", READY, 10, "easy", 5, None,
        "Get your bag ready for a day out or a club, without forgetting anything.",
        [("1", "bag"), ("", "a picture or word checklist")],
        ["Make a checklist together with pictures or words: water bottle, snack, coat, hat, and anything special for today.",
         "Collect everything on the list and put it beside your bag.",
         "Put the heaviest thing in first.",
         "Tick each thing off as it goes in.",
         "Zip the bag up and put it by the front door, ready to go."],
        "Packing the night before makes mornings much calmer.",
    ),
    _item(
        "life", "life-young-sort-washing", "Sort and pair the washing", "🧦", HELPING, 15, "easy", 3, None,
        "Match the socks, fold the clothes and put them away. Sorting and matching is good maths too.",
        [("", "a basket of clean, dry washing")],
        ["Tip the clean washing onto a bed or table.",
         "Find all the socks and match them into pairs.",
         "Fold each pair together so they don't get lost.",
         "Sort the rest into a pile for each person in the family.",
         "Fold T-shirts in half, then in half again.",
         "Carry your own pile to your room and put it away."],
        "Count the socks as you go. Is there an odd one left over?",
    ),
    _item(
        "life", "life-young-make-sandwich", "Make a sandwich", "🥪", KNOWHOW, 15, "easy", 5, None,
        "Make your own lunch from start to finish, including the clearing up.",
        [("2 slices", "bread"), ("", "butter or spread"), ("", "a filling, such as cheese, ham or cucumber"), ("", "a table knife and a plate")],
        ["Wash your hands.",
         "Put two slices of bread on your plate.",
         "Spread butter thinly on one side of each slice with a table knife.",
         "Add your filling to one slice.",
         "Put the other slice on top, butter side down.",
         ("Cut the sandwich in half. A grown-up helps with a sharper knife if it's needed.", G),
         "Put everything away and wipe the table."],
        "Cut it into triangles, squares or fingers. Which shape tastes best?",
    ),
]
