"""Wellies: the P.E. and active-play ideas every family starts with. Written for Bright Roots.

Ten for one child on their own and ten for a group (siblings, friends or a home-ed meet-up).
Kept in sync on start-up by slug, like the recipes and crafts.
"""
from make_starters import G, _item

SOLO = "On your own"
GROUP = "Group games"

PE_SOLO = [
    _item(
        "pe", "pe-obstacle-course", "Garden obstacle course", "🏃", SOLO, 30, "easy", 3, "1 child",
        "Build a course from things around the house and garden, then beat your own time.",
        [("", "cushions, chairs, a broom, hoops or buckets"), ("", "a timer or phone")],
        [("Help set up 5 to 8 stations: crawl under a chair, jump over the broom, zig-zag round buckets.", G),
         "Walk the course slowly first so you know the way.",
         "Run it while a grown-up times you.",
         "Try again and see if you can beat your time.",
         "Swap one station for a new challenge, like hopping or crab-walking."],
        "Let them design the course themselves: planning the order is good thinking practice too.",
    ),
    _item(
        "pe", "pe-animal-moves", "Animal moves", "🐻", SOLO, 15, "easy", 3, "1 child",
        "Move like different animals across the room. Great for strength, balance and giggles.",
        [("", "a clear space"), ("", "animal cards or a grown-up calling them out")],
        ["Bear walk: hands and feet on the floor, bottom up high.",
         "Frog jumps: squat low and spring forward.",
         "Crab walk: sit, hands behind you, lift your tummy and walk.",
         "Flamingo: stand on one leg for as long as you can.",
         "Snake slither: lie on your tummy and wriggle along.",
         "Finish by making up your own animal move."],
        "Say the animal and let them invent the move first, then try the 'proper' way.",
    ),
    _item(
        "pe", "pe-skipping-challenge", "Skipping challenge", "🪢", SOLO, 15, "medium", 5, "1 child",
        "Build up skipping skills from single jumps to tricks, and keep a record of your best.",
        [("1", "skipping rope (or a long piece of washing line)")],
        ["Jump over the rope laid still on the ground, forwards and backwards.",
         "Turn the rope over your head and step over it slowly.",
         "Now jump it: count how many in a row.",
         "Try one-foot hops or crossing your arms if it's getting easy.",
         "Write down your best score and try to beat it next week."],
        "Rope too long? Stand on the middle: the handles should reach the armpits.",
    ),
    _item(
        "pe", "pe-yoga-story", "Story yoga", "🧘", SOLO, 20, "easy", 3, "1 child",
        "A calm session where each yoga pose is part of a story. Lovely for winding down.",
        [("", "a mat or towel"), ("", "a quiet space")],
        ["Mountain: stand tall and still like a big mountain.",
         "Tree: one foot on the other leg, arms up like branches blowing in the wind.",
         "Cat and cow: on hands and knees, round your back then dip it.",
         "Downward dog: hands and feet down, bottom to the sky.",
         "Butterfly: sit with feet together and flap your knees.",
         "Sleeping lion: lie still with eyes closed and take five slow breaths."],
        "Make up the story together: 'We climbed the mountain and saw a tree...'",
    ),
    _item(
        "pe", "pe-balloon-keepy-uppy", "Balloon keepy-uppy", "🎈", SOLO, 10, "easy", 3, "1 child",
        "Keep a balloon off the floor using hands, feet, knees and heads. Perfect for rainy days.",
        [("1", "balloon")],
        ["Tap the balloon up with your hands and count the touches.",
         "Now use only one hand, then only the other.",
         "Try feet, knees, elbows and head.",
         "Challenge: clap before every touch.",
         "Beat your best count."],
        "Balloons can pop and are a choking hazard for little ones, so keep an eye on the pieces.",
    ),
    _item(
        "pe", "pe-target-throwing", "Target throwing", "🎯", SOLO, 20, "easy", 4, "1 child",
        "Throw bean bags or rolled socks into buckets from further and further away.",
        [("3", "buckets, boxes or hoops"), ("6", "bean bags or rolled-up socks"), ("", "chalk or tape for lines")],
        ["Put the targets out at different distances and give them points: 1, 3 and 5.",
         "Mark a throwing line.",
         "Throw underarm first, then overarm.",
         "Add up your score after six throws.",
         "Step back a big step and try again."],
        "Adding the scores is sneaky maths practice.",
    ),
    _item(
        "pe", "pe-dance-freeze", "Dance and freeze", "💃", SOLO, 15, "easy", 3, "1 child",
        "Dance to music and freeze like a statue when it stops. Hold a funny pose!",
        [("", "music you can pause")],
        ["Put on some music and dance any way you like.",
         "When the music stops, freeze!",
         "Hold a funny pose until it starts again.",
         "Try freezing in a shape: a star, a ball, a letter.",
         "Take a turn being the one who stops the music."],
    ),
    _item(
        "pe", "pe-hopscotch", "Hopscotch", "🔢", SOLO, 20, "easy", 4, "1 child",
        "Chalk a hopscotch grid and hop, jump and balance your way to the top.",
        [("", "chalk"), ("1", "small stone or bean bag")],
        ["Draw a grid of squares numbered 1 to 10.",
         "Throw the stone onto square 1.",
         "Hop over that square, hopping on single squares and jumping on doubles.",
         "Turn round at the top and hop back, picking up the stone on the way.",
         "Throw to square 2 next, and keep going."],
        "No chalk or pavement? Use masking tape on the floor indoors.",
    ),
    _item(
        "pe", "pe-fitness-dice", "Fitness dice", "🎲", SOLO, 15, "medium", 6, "1 child",
        "Roll a die to pick an exercise and another to pick how many. Quick, random and fun.",
        [("2", "dice"), ("", "a list of 6 exercises")],
        ["Write a list numbered 1 to 6: star jumps, squats, hops, lunges, sit-ups, spins.",
         "Roll the first die to choose the exercise.",
         "Roll the second die and double it for how many.",
         "Do them, then roll again.",
         "Stop after 10 rolls and have a drink of water."],
        "Older children can write their own list or make the numbers harder.",
    ),
    _item(
        "pe", "pe-nature-run", "Nature scavenger run", "🌳", SOLO, 30, "easy", 4, "1 child",
        "Run or jog around the park or garden finding things on a list before the timer ends.",
        [("1", "list of things to find"), ("1", "bag"), ("", "a timer")],
        [("Choose a safe area and agree where the edges are.", G),
         "Read the list: a feather, three different leaves, something round, a stick shaped like a letter...",
         "Start the timer and run to find them.",
         "Jog back to base with each find.",
         "Count how many you got before time ran out."],
        "Wear wellies if it's muddy!",
    ),
]

PE_GROUP = [
    _item(
        "pe", "pe-tag-games", "Tag games", "🏃", GROUP, 20, "easy", 4, "3 or more",
        "Classic chasing games with fun twists: stuck in the mud, shadow tag and more.",
        [("", "a space to run"), ("", "cones or jumpers to mark edges")],
        ["Mark out the playing area.",
         "Stuck in the mud: when tagged, stand still with legs apart until someone crawls through.",
         "Shadow tag: tag someone by stepping on their shadow.",
         "Toilet tag: tagged players stand with one arm out until someone 'flushes' them free.",
         "Swap who's 'it' every couple of minutes."],
    ),
    _item(
        "pe", "pe-relay-races", "Relay races", "🏁", GROUP, 25, "easy", 4, "4 or more",
        "Team races passing a baton, with silly styles like egg-and-spoon or backwards walking.",
        [("1", "baton per team (a rolled-up newspaper works)"), ("", "cones or markers"),
         ("", "spoons and potatoes or bean bags")],
        ["Split into two teams and line up at the start.",
         "The first runner goes round the far cone and back, then hands over the baton.",
         "First team to finish wins the round.",
         "Next rounds: hopping, egg-and-spoon, walking backwards, crab walk.",
         "Finish with a normal sprint relay."],
    ),
    _item(
        "pe", "pe-parachute-games", "Parachute games", "🪂", GROUP, 20, "easy", 3, "4 or more",
        "Wave a play parachute (or a big old sheet) together to make waves, mushrooms and a popcorn storm.",
        [("1", "play parachute or large sheet"), ("", "soft balls")],
        ["Everyone holds the edge and makes small waves, then big waves.",
         "Mushroom: lift it high together and step in underneath.",
         "Popcorn: throw balls on top and shake them off as fast as you can.",
         "Swap places: call two names, they run under to swap before it comes down.",
         "Finish by lying under it while the grown-ups gently float it down."],
    ),
    _item(
        "pe", "pe-football-skills", "Football skills circuit", "⚽", GROUP, 30, "medium", 5, "2 or more",
        "Dribbling, passing and shooting stations, ending in a mini match.",
        [("1", "football"), ("6", "cones or jumpers"), ("", "a goal (two jumpers)")],
        ["Dribble: weave the ball in and out of a line of cones.",
         "Pass: stand opposite a partner and pass back and forth ten times.",
         "Shoot: take turns shooting at the goal from a marked spot.",
         "Keepy-uppy: count how many you can do.",
         "Finish with a five-minute mini match."],
    ),
    _item(
        "pe", "pe-simon-says", "Simon says: fitness", "🗣️", GROUP, 15, "easy", 3, "2 or more",
        "The classic listening game, but every command is an exercise.",
        [("", "a clear space")],
        ["One person is Simon and calls out moves: 'Simon says do five star jumps!'",
         "Everyone does the move only if Simon says it.",
         "If Simon doesn't say 'Simon says', stand still!",
         "Anyone caught out does 3 squats and joins back in.",
         "Take turns being Simon."],
    ),
    _item(
        "pe", "pe-rounders", "Garden rounders", "🏏", GROUP, 40, "medium", 6, "4 or more",
        "A mini game of rounders with four bases and a soft ball.",
        [("1", "bat (or a tennis racket)"), ("1", "soft ball"), ("4", "markers for bases")],
        ["Set out four bases in a diamond and a spot for the bowler.",
         "One team bats, the other fields.",
         "The batter hits and runs to as many bases as they can.",
         "Get round all four for a rounder!",
         "Swap teams after everyone has batted."],
        "Little ones can hit from a tee (a cone or upturned bucket) instead of a bowled ball.",
    ),
    _item(
        "pe", "pe-capture-the-flag", "Capture the flag", "🚩", GROUP, 30, "medium", 6, "6 or more",
        "Two teams each guard a flag and try to sneak the other team's back to their side.",
        [("2", "flags (tea towels or bibs)"), ("", "cones or jumpers for a halfway line")],
        ["Split the area in half with a line and put a flag at the back of each half.",
         "Players who are tagged on the other side go to 'jail' and wait to be freed.",
         "Grab the other team's flag and bring it home to win.",
         "Play first to two flags.",
         "Talk about tactics between rounds: who guards, who attacks?"],
    ),
    _item(
        "pe", "pe-tug-of-war", "Tug of war", "🪢", GROUP, 15, "easy", 5, "4 or more",
        "Two teams pull on a rope to drag the other over a line. Teamwork and strength!",
        [("1", "long thick rope"), ("1", "ribbon for the middle"), ("", "a line on the ground")],
        [("Check the ground is soft (grass is best) and there's nothing to trip over.", G),
         "Tie the ribbon in the middle of the rope over the line.",
         "Teams hold the rope on either side. Bend knees, lean back.",
         "On 'pull!', each team pulls until the ribbon crosses into their side.",
         "Best of three wins."],
        "Never wrap the rope around hands or waists.",
    ),
    _item(
        "pe", "pe-sports-day", "Mini sports day", "🏅", GROUP, 60, "easy", 3, "3 or more",
        "Sack race, egg-and-spoon, bean bag throw and a sprint, with medals at the end.",
        [("", "pillowcases for sacks"), ("", "spoons and potatoes"), ("", "bean bags"), ("", "homemade medals")],
        ["Plan four events and write them on a scoreboard.",
         "Run each event, cheering everyone on.",
         "Give points for taking part as well as for winning.",
         "Finish with a grown-ups' race!",
         "Hand out medals and certificates."],
        "Make the medals together beforehand from card and ribbon.",
    ),
    _item(
        "pe", "pe-duck-duck-goose", "Duck, duck, goose", "🦆", GROUP, 15, "easy", 3, "4 or more",
        "Sit in a circle, tap heads saying 'duck'... then 'goose!' and race round the circle.",
        [("", "a space to sit in a circle")],
        ["Everyone sits in a circle facing in.",
         "One person walks round tapping heads: 'duck, duck, duck...'",
         "They choose someone and say 'goose!'",
         "The goose chases them round the circle.",
         "If the walker reaches the empty spot, the goose is the new walker."],
    ),
]
