"""The recipes and crafts every family starts with. Written for Bright Roots.

They are kept in sync on every start-up (matched by slug), so edits here reach every family
on the next deploy. Families' own recipes and crafts are never touched.
"""
import json

from sqlalchemy.orm import Session

from models import MakeItem

G = True  # marks a step for a grown-up


def _item(kind, slug, title, emoji, category, minutes, difficulty, age_from, serves, summary, materials, steps, tips=None):
    return {
        "kind": kind,
        "slug": slug,
        "title": title,
        "emoji": emoji,
        "category": category,
        "minutes": minutes,
        "difficulty": difficulty,
        "age_from": age_from,
        "serves": serves,
        "summary": summary,
        "materials": [{"name": n, "qty": q} for q, n in materials],
        "steps": [{"text": s[0], "grown_up": bool(s[1])} if isinstance(s, tuple) else {"text": s, "grown_up": False} for s in steps],
        "tips": tips,
    }


RECIPES = [
    _item(
        "recipe", "pizza-faces", "Pizza faces", "🍕", "Lunch", 25, "easy", 3, "4 pizzas",
        "Tiny pizzas on muffin halves, decorated with silly faces before they go in the oven.",
        [("2", "English muffins"), ("4 tbsp", "tomato purée or passata"), ("100 g", "grated cheese"),
         ("1", "pepper"), ("4", "cherry tomatoes"), ("a few", "olives or sweetcorn")],
        [("Heat the oven to 200°C (180°C fan, gas 6).", G),
         "Split the muffins in half and put them on a baking tray, cut side up.",
         "Spread a spoonful of tomato over each half, right to the edges.",
         "Sprinkle over the cheese.",
         ("Slice the pepper and halve the tomatoes.", G),
         "Make a face on each pizza: tomato eyes, pepper smiles, sweetcorn freckles!",
         ("Bake for 8 to 10 minutes until the cheese is bubbling.", G),
         "Let them cool for a few minutes before eating."],
        "Pitta breads or wraps work just as well as muffins.",
    ),
    _item(
        "recipe", "banana-muffins", "Banana muffins", "🍌", "Baking", 35, "easy", 4, "12 muffins",
        "A great way to use up spotty bananas. Mashing is the best bit.",
        [("3", "ripe bananas"), ("75 g", "melted butter"), ("100 g", "soft brown sugar"), ("1", "egg"),
         ("1 tsp", "vanilla extract"), ("200 g", "self-raising flour"), ("1 tsp", "baking powder")],
        [("Heat the oven to 180°C (160°C fan, gas 4) and put 12 cases in a muffin tin.", G),
         "Mash the bananas in a big bowl with a fork until they're squishy.",
         "Stir in the melted butter, sugar, egg and vanilla.",
         "Add the flour and baking powder and fold gently until you can't see any flour.",
         "Spoon the mixture into the cases, about two-thirds full.",
         ("Bake for 20 to 22 minutes until risen and golden.", G),
         "Leave to cool on a rack."],
        "Add a handful of chocolate chips or blueberries for a treat.",
    ),
    _item(
        "recipe", "rainbow-fruit-skewers", "Rainbow fruit skewers", "🌈", "Snacks", 15, "easy", 3, "6 skewers",
        "Thread fruit in rainbow order. A tasty way to learn the colours.",
        [("6", "strawberries"), ("1", "orange or satsuma"), ("1", "banana"), ("1 handful", "green grapes"),
         ("1 handful", "blueberries"), ("1 handful", "red grapes"), ("6", "wooden skewers")],
        [("Snip the sharp tips off the skewers.", G),
         "Wash the fruit.",
         "Peel the orange and banana and break them into chunks.",
         "Thread the fruit in rainbow order: red, orange, yellow, green, blue, purple.",
         "Can you say each colour as you go?"],
        "Serve with a spoonful of yoghurt to dip.",
    ),
    _item(
        "recipe", "two-ingredient-flatbreads", "Easy flatbreads", "🫓", "Lunch", 25, "easy", 4, "4 flatbreads",
        "Soft flatbreads made from just yoghurt and flour. Brilliant for little hands to knead.",
        [("200 g", "self-raising flour"), ("200 g", "plain yoghurt"), ("a pinch", "salt"),
         ("a little", "extra flour for dusting")],
        ["Mix the flour, yoghurt and salt in a bowl with a spoon, then with your hands.",
         "Tip the dough onto a floury table and knead it for 2 minutes until smooth.",
         "Cut it into 4 pieces and roll each one into a ball.",
         "Flatten each ball with a rolling pin until it's about as thin as a coin.",
         ("Cook each flatbread in a hot, dry frying pan for 2 minutes on each side until puffy with brown spots.", G)],
        "Fill with cheese and salad, or dip in soup.",
    ),
    _item(
        "recipe", "cheese-scones", "Cheese scones", "🧀", "Baking", 35, "medium", 5, "8 scones",
        "Crumbly, cheesy scones. Rubbing in the butter feels like making sand.",
        [("225 g", "self-raising flour"), ("1 tsp", "baking powder"), ("50 g", "cold butter"),
         ("100 g", "grated cheddar"), ("125 ml", "milk"), ("a pinch", "salt")],
        [("Heat the oven to 220°C (200°C fan, gas 7) and line a baking tray.", G),
         "Put the flour, baking powder and salt in a bowl.",
         "Cut the butter into cubes and rub it into the flour with your fingertips until it looks like breadcrumbs.",
         "Stir in most of the cheese, keeping a little for the tops.",
         "Pour in the milk and mix to a soft dough.",
         "Pat the dough out until it's as thick as your thumb and cut out rounds with a cutter.",
         "Put them on the tray and sprinkle the rest of the cheese on top.",
         ("Bake for 12 to 15 minutes until golden.", G)],
        "Don't twist the cutter, just press straight down, and they'll rise taller.",
    ),
    _item(
        "recipe", "oat-flapjacks", "Oaty flapjacks", "🥣", "Baking", 40, "easy", 4, "12 squares",
        "Chewy, golden oat bars. Perfect for picnics and lunchboxes.",
        [("125 g", "butter"), ("100 g", "soft brown sugar"), ("3 tbsp", "golden syrup"),
         ("250 g", "porridge oats"), ("1 handful", "raisins")],
        [("Heat the oven to 180°C (160°C fan, gas 4) and line a square tin.", G),
         ("Melt the butter, sugar and syrup together in a pan over a low heat.", G),
         "Measure the oats and raisins into a big bowl.",
         "Pour in the melted mixture and stir until every oat is shiny.",
         "Tip it into the tin and press it flat with the back of a spoon.",
         ("Bake for 20 to 25 minutes until golden at the edges.", G),
         "Cut into squares while warm, then leave to cool in the tin."],
    ),
    _item(
        "recipe", "mini-frittatas", "Mini veggie frittatas", "🥚", "Lunch", 30, "medium", 5, "12 mini frittatas",
        "Little egg muffins packed with veg. Great warm or cold.",
        [("6", "eggs"), ("3 tbsp", "milk"), ("50 g", "grated cheese"), ("1", "pepper"),
         ("1 handful", "spinach"), ("2", "spring onions"), ("a little", "oil for the tin")],
        [("Heat the oven to 180°C (160°C fan, gas 4) and oil a 12-hole muffin tin.", G),
         ("Chop the pepper and spring onions into small pieces.", G),
         "Crack the eggs into a jug and whisk with the milk.",
         "Tear the spinach into small pieces.",
         "Share the veg and cheese between the holes of the tin.",
         "Carefully pour the egg over the top, filling each hole three-quarters full.",
         ("Bake for 15 to 18 minutes until puffed up and set.", G)],
    ),
    _item(
        "recipe", "chocolate-crispy-cakes", "Chocolate crispy cakes", "🍫", "Treats", 20, "easy", 3, "12 cakes",
        "A party classic with no oven needed. Just melt, stir and set.",
        [("200 g", "milk chocolate"), ("50 g", "butter"), ("2 tbsp", "golden syrup"),
         ("100 g", "cornflakes or rice pops"), ("12", "paper cases")],
        [("Melt the chocolate, butter and syrup in a bowl over a pan of barely simmering water, or in short bursts in the microwave.", G),
         "Tip the cereal into a big bowl.",
         "Pour over the chocolate and stir gently until everything is coated.",
         "Spoon into the paper cases.",
         "Put them in the fridge for an hour to set."],
        "Add mini eggs on top at Easter, or sprinkles for birthdays.",
    ),
    _item(
        "recipe", "traffic-light-pasta-salad", "Traffic light pasta salad", "🚦", "Lunch", 25, "easy", 4, "4 bowls",
        "Red, amber and green veg stirred through pasta. A colourful packed lunch.",
        [("200 g", "pasta shapes"), ("1", "red pepper"), ("1", "yellow pepper"), ("1", "cucumber"),
         ("1 small tin", "sweetcorn"), ("3 tbsp", "mayonnaise or pesto")],
        [("Cook the pasta following the packet, then drain and cool it under cold water.", G),
         ("Chop the peppers and cucumber into small cubes.", G),
         "Drain the sweetcorn.",
         "Put everything in a big bowl with the mayonnaise or pesto.",
         "Stir it all together. Can you spot red, amber and green?"],
    ),
    _item(
        "recipe", "berry-smoothie", "Berry banana smoothie", "🥤", "Drinks", 10, "easy", 3, "2 glasses",
        "A thick, pink smoothie. Quick, easy and full of fruit.",
        [("1", "banana"), ("150 g", "frozen berries"), ("150 g", "plain yoghurt"), ("200 ml", "milk"),
         ("1 tsp", "honey (optional)")],
        ["Peel the banana and break it into pieces.",
         "Put everything into the blender jug.",
         ("Put the lid on firmly and blend until smooth.", G),
         "Pour into glasses and enjoy straight away."],
        "Honey isn't suitable for babies under 1.",
    ),
    _item(
        "recipe", "shortbread-biscuits", "Shortbread biscuits", "🍪", "Baking", 40, "easy", 4, "about 16 biscuits",
        "Buttery biscuits made from just three ingredients. Cut them into any shape you like.",
        [("150 g", "plain flour"), ("100 g", "softened butter"), ("50 g", "caster sugar"),
         ("a little", "extra sugar for sprinkling")],
        [("Heat the oven to 180°C (160°C fan, gas 4) and line a baking tray.", G),
         "Beat the butter and sugar together until smooth and pale.",
         "Add the flour and mix with your hands until it comes together into a dough.",
         "Roll it out on a floury table until it's as thick as a pound coin.",
         "Cut out shapes and put them on the tray.",
         ("Bake for 12 to 15 minutes until just turning golden at the edges.", G),
         "Sprinkle with a little sugar and leave to cool. They firm up as they cool."],
    ),
    _item(
        "recipe", "hummus-dippers", "Hummus and veggie dippers", "🥕", "Snacks", 15, "easy", 4, "4 people",
        "Whizz up your own hummus and dunk crunchy vegetables in it.",
        [("1 tin", "chickpeas"), ("1", "lemon"), ("2 tbsp", "olive oil"), ("1 tbsp", "tahini (optional)"),
         ("1 small clove", "garlic"), ("2", "carrots"), ("1", "cucumber"), ("1", "pepper")],
        ["Drain the chickpeas, keeping a little of the water from the tin.",
         "Squeeze the juice from the lemon.",
         ("Blend the chickpeas, lemon juice, oil, tahini and garlic until smooth, adding a splash of the chickpea water if it's too thick.", G),
         ("Cut the carrots, cucumber and pepper into sticks.", G),
         "Spoon the hummus into a bowl and arrange the dippers around it."],
        "Some children are allergic to sesame, which is in tahini. You can leave it out.",
    ),
]

CRAFTS = [
    _item(
        "craft", "salt-dough", "Salt dough decorations", "⭐", "Modelling", 60, "easy", 3, None,
        "Make shapes from salt dough, bake them hard, then paint them. Lovely as gifts or decorations.",
        [("250 g", "plain flour"), ("125 g", "table salt"), ("125 ml", "water"), ("", "cookie cutters"),
         ("", "a straw"), ("", "paints and brushes"), ("", "ribbon or string")],
        ["Mix the flour and salt in a bowl.",
         "Add the water a little at a time and squish it into a smooth dough.",
         "Roll it out until it's about as thick as your finger.",
         "Cut out shapes with cookie cutters, or press in handprints.",
         "Poke a hole near the top of each one with a straw, for hanging.",
         ("Bake at 100°C (80°C fan, gas ¼) for about 2 to 3 hours until hard, then leave to cool.", G),
         "Paint your shapes and let them dry.",
         "Thread ribbon through the holes to hang them up."],
        "Salt dough isn't for eating, so keep an eye on little ones.",
    ),
    _item(
        "craft", "paper-plate-lion", "Paper plate lion", "🦁", "Paper", 30, "easy", 3, None,
        "A roaring lion with a fluffy mane, made from a paper plate.",
        [("1", "paper plate"), ("", "yellow and orange paint or crayons"), ("", "orange and brown paper"),
         ("", "child-safe scissors"), ("", "glue stick"), ("", "black pen")],
        ["Colour or paint the middle of the plate yellow for the lion's face.",
         "Cut strips of orange and brown paper for the mane.",
         "Glue the strips all the way round the edge of the plate.",
         "Curl some strips round a pencil to make them extra fluffy.",
         "Draw on eyes, a nose, a mouth and whiskers.",
         "Give your lion a name and a big ROAR!"],
        "Try other animals too: a pink pig, a stripy tiger or a spotty ladybird.",
    ),
    _item(
        "craft", "pine-cone-bird-feeder", "Pine cone bird feeder", "🐦", "Nature", 30, "easy", 3, None,
        "Help the garden birds through winter, then watch who comes to visit.",
        [("1", "large pine cone"), ("", "string"), ("3 tbsp", "lard or vegetable suet"),
         ("1 cup", "bird seed"), ("", "a butter knife"), ("", "a plate or tray")],
        ["Tie a long piece of string round the top of the pine cone.",
         "Spread lard into all the gaps in the cone with a butter knife.",
         "Pour the bird seed onto a plate.",
         "Roll the sticky cone in the seed until it's covered.",
         "Hang it on a tree branch, somewhere you can see from a window.",
         "Keep a tally of which birds visit!"],
        "Don't use peanut butter with added salt, and wash hands after touching the lard.",
    ),
    _item(
        "craft", "toilet-roll-binoculars", "Explorer binoculars", "🔭", "Recycling", 20, "easy", 3, None,
        "Turn two cardboard tubes into binoculars for a nature hunt or safari.",
        [("2", "toilet roll tubes"), ("", "paint, pens or stickers"), ("", "sticky tape"),
         ("", "hole punch"), ("", "string or wool")],
        ["Decorate the two tubes any way you like.",
         "Put them side by side and tape them together.",
         "Punch a hole on the outside edge of each tube.",
         "Tie a piece of string through the holes to make a neck strap.",
         "Head outside and see what you can spot!"],
    ),
    _item(
        "craft", "leaf-rubbings", "Leaf rubbings", "🍂", "Nature", 30, "easy", 3, None,
        "Collect leaves, then rub over them to reveal their veins and patterns.",
        [("", "leaves of different shapes"), ("", "plain paper"), ("", "wax crayons with the paper peeled off")],
        ["Go on a walk and collect leaves of different shapes and sizes.",
         "Put a leaf on the table, bumpy side up.",
         "Lay a sheet of paper on top.",
         "Rub the side of a crayon gently over the paper until the leaf appears.",
         "Try different colours and overlap the leaves to make a pattern.",
         "Can you find out which tree each leaf came from?"],
    ),
    _item(
        "craft", "homemade-playdough", "Soft homemade playdough", "🎨", "Modelling", 20, "easy", 2, None,
        "Soft, stretchy playdough that lasts for weeks in a sealed bag.",
        [("2 cups", "plain flour"), ("½ cup", "table salt"), ("2 tbsp", "cream of tartar"),
         ("2 tbsp", "vegetable oil"), ("1½ cups", "boiling water"), ("", "food colouring")],
        ["Mix the flour, salt and cream of tartar in a big bowl.",
         "Add the oil and a few drops of food colouring.",
         ("Pour in the boiling water and stir with a wooden spoon.", G),
         ("When it's cool enough to touch, knead it on the table for a few minutes until smooth.", G),
         "Now squash, roll and shape it!",
         "Store it in a sealed bag or tub."],
        "It's not for eating, even though it's made from food.",
    ),
    _item(
        "craft", "butterfly-prints", "Symmetry butterfly prints", "🦋", "Painting", 20, "easy", 3, None,
        "Paint on one side, fold, and a butterfly appears. A fun way to learn about symmetry.",
        [("", "paper"), ("", "poster paints"), ("", "brushes or spoons"), ("", "child-safe scissors")],
        ["Fold a sheet of paper in half, then open it out again.",
         "Blob paint on one side of the fold only.",
         "Fold the paper closed and press firmly all over.",
         "Open it up to reveal the pattern: both sides match!",
         "When it's dry, cut out a butterfly shape round your pattern."],
        "Talk about symmetry: where else can you find matching halves?",
    ),
    _item(
        "craft", "painted-rocks", "Painted story stones", "🪨", "Painting", 45, "easy", 4, None,
        "Paint pictures on smooth stones, then use them to tell stories.",
        [("6–10", "smooth stones"), ("", "acrylic or poster paint"), ("", "fine brushes or paint pens"),
         ("", "PVA glue (optional, to seal)")],
        ["Wash and dry your stones.",
         "Paint each one a background colour and let it dry.",
         "Paint a picture on each stone: an animal, a house, a sun, a tree, a character.",
         "When dry, brush on a layer of PVA glue to make them shiny.",
         "Put them in a bag, pull out three and make up a story that uses them all!"],
    ),
    _item(
        "craft", "sock-puppets", "Sock puppets", "🧦", "Recycling", 30, "easy", 4, None,
        "Give odd socks a new life as puppet characters, then put on a show.",
        [("1", "old sock"), ("", "buttons or googly eyes"), ("", "felt or paper scraps"),
         ("", "wool for hair"), ("", "fabric glue")],
        ["Put the sock on your hand to see where the eyes and mouth go.",
         "Take it off and glue on eyes where your knuckles were.",
         "Cut a tongue from red felt and glue it inside the mouth.",
         "Add hair, ears, a nose or anything else you like.",
         "Leave it to dry, then put on a puppet show!"],
        "Buttons are a choking hazard for under-3s, so draw eyes on instead.",
    ),
    _item(
        "craft", "paper-plate-tambourine", "Paper plate tambourine", "🥁", "Music", 25, "easy", 3, None,
        "A shaky, rattly instrument made from two paper plates.",
        [("2", "paper plates"), ("1 handful", "dried rice or lentils"), ("", "stapler or strong tape"),
         ("", "paints or pens"), ("", "ribbons")],
        ["Decorate the bottom of both plates.",
         "Put a handful of rice on one plate.",
         ("Put the other plate on top, face down, and staple all the way round the edge so nothing can escape.", G),
         "Tape ribbons round the edge.",
         "Shake it, tap it and make some music!"],
    ),
    _item(
        "craft", "tissue-window", "Stained glass window", "🪟", "Paper", 30, "easy", 4, None,
        "Tissue paper on sticky-back plastic makes a bright window picture that glows in the sun.",
        [("", "sticky-back plastic"), ("", "coloured tissue paper"), ("", "black card"),
         ("", "child-safe scissors"), ("", "sticky tape")],
        [("Cut a frame shape from black card, like a heart, circle or star.", G),
         "Peel the backing off a piece of sticky-back plastic and lay it sticky side up.",
         "Press the frame onto it.",
         "Tear or cut small pieces of tissue paper and stick them inside the frame.",
         "Cover with a second piece of plastic to seal it.",
         "Trim the edges and tape it to a sunny window."],
    ),
    _item(
        "craft", "pasta-necklace", "Painted pasta necklace", "📿", "Threading", 40, "easy", 3, None,
        "Paint pasta tubes in bright colours and thread them into jewellery. Great for fine motor skills.",
        [("1 handful", "penne or rigatoni pasta"), ("", "poster paint"), ("", "brushes"),
         ("", "string or wool"), ("", "sticky tape")],
        ["Paint the pasta tubes in lots of colours and leave them to dry.",
         "Wrap tape round one end of the string to make a stiff needle.",
         "Thread the pasta on, making a pattern: red, blue, red, blue...",
         ("Tie the ends together, checking it fits easily over their head.", G),
         "Wear it with pride!"],
        "Make patterns to practise sequencing: can someone else guess what comes next?",
    ),
]


def seed_starters(db: Session) -> None:
    """Create or update every starter recipe and craft."""
    for data in RECIPES + CRAFTS:
        item = db.query(MakeItem).filter(MakeItem.slug == data["slug"]).first()
        if item is None:
            item = MakeItem(slug=data["slug"], parent_id=None)
            db.add(item)
        for key, value in data.items():
            if key in ("materials", "steps"):
                value = json.dumps(value)
            setattr(item, key, value)
    db.commit()
