"""Teen Corner: recipes and projects for ages 11 to 16. Written for Bright Roots.

Steps are written for the teenager to do on their own. "Grown-up" marks are kept for the few
genuinely risky jobs.
"""
from make_starters import G, _item

TEEN_RECIPES = [
    _item(
        "recipe", "teen-spaghetti-bolognese", "Spaghetti bolognese", "🍝", "Dinners", 50, "medium", 11, "4 people",
        "A proper family dinner you can cook from start to finish. Master this and you've got a meal for life.",
        [("1", "onion"), ("1", "carrot"), ("2 cloves", "garlic"), ("1 tbsp", "olive oil"), ("500 g", "beef mince"),
         ("1 tin", "chopped tomatoes"), ("2 tbsp", "tomato purée"), ("1 tsp", "dried oregano"),
         ("1", "stock cube"), ("300 g", "spaghetti"), ("", "grated cheese to serve")],
        ["Finely chop the onion, grate the carrot and crush the garlic.",
         "Heat the oil in a large pan over a medium heat and soften the onion and carrot for 5 minutes.",
         "Add the garlic and cook for 1 minute, then add the mince and break it up with a wooden spoon until it's browned all over.",
         "Stir in the tomatoes, purée and oregano, and crumble in the stock cube with 150 ml of water.",
         "Simmer with the lid half on for 25 minutes, stirring now and then. Taste and add salt and pepper if needed.",
         "While it simmers, cook the spaghetti in a big pan of salted boiling water for the time on the packet.",
         ("Drain the pasta carefully over the sink, pouring away from you.", G),
         "Serve the sauce on the spaghetti with grated cheese."],
        "Swap the mince for lentils or plant-based mince to make it veggie. Leftover sauce freezes well.",
    ),
    _item(
        "recipe", "teen-veggie-stir-fry", "Veggie noodle stir-fry", "🥢", "Dinners", 25, "easy", 11, "2 people",
        "Fast, colourful and ready in the time it takes to boil noodles. Great for learning knife skills.",
        [("2 nests", "egg or rice noodles"), ("1", "pepper"), ("1", "carrot"), ("1 handful", "mangetout or broccoli"),
         ("2", "spring onions"), ("1 thumb", "ginger"), ("1 clove", "garlic"), ("1 tbsp", "vegetable oil"),
         ("3 tbsp", "soy sauce"), ("1 tbsp", "honey"), ("1 tsp", "sesame oil (optional)")],
        ["Cook the noodles following the packet, drain and toss with a splash of oil so they don't stick.",
         "Slice the pepper, cut the carrot into thin matchsticks and slice the spring onions.",
         "Grate the ginger and garlic.",
         "Mix the soy sauce, honey and sesame oil in a cup.",
         "Heat the oil in a wok or big frying pan until very hot, then stir-fry the veg for 3 to 4 minutes, keeping everything moving.",
         "Add the ginger and garlic for 30 seconds, then the noodles and sauce. Toss for 1 minute until glossy and hot."],
        "Add cooked chicken, prawns or tofu for extra protein.",
    ),
    _item(
        "recipe", "teen-pizza-from-scratch", "Pizza from scratch", "🍕", "Dinners", 90, "medium", 11, "2 large pizzas",
        "Make real pizza dough, let it rise, then top it however you like. Better than a takeaway.",
        [("500 g", "strong white bread flour"), ("7 g sachet", "fast-action yeast"), ("1 tsp", "salt"),
         ("300 ml", "warm water"), ("2 tbsp", "olive oil"), ("200 g", "passata"), ("250 g", "mozzarella"),
         ("", "toppings of your choice")],
        ["Mix the flour, yeast and salt in a big bowl. Make a well and pour in the warm water and oil.",
         "Stir to a rough dough, then knead on a floured surface for 10 minutes until smooth and stretchy.",
         "Put it back in the bowl, cover with a tea towel and leave somewhere warm for an hour until doubled in size.",
         "Heat the oven to 240°C (220°C fan, gas 9) with two baking trays inside.",
         "Knock the air out of the dough, split it in two and roll or stretch each half into a thin circle.",
         "Spread with passata, tear over the mozzarella and add your toppings.",
         ("Carefully slide the pizzas onto the hot trays using oven gloves.", G),
         "Bake for 10 to 12 minutes until the base is crisp and the cheese is bubbling."],
        "The dough can rise slowly in the fridge overnight. Just let it warm up for 30 minutes before rolling.",
    ),
    _item(
        "recipe", "teen-chicken-curry", "Easy chicken curry", "🍛", "Dinners", 45, "medium", 12, "4 people",
        "A mild, creamy curry with rice. Learn how spices build flavour.",
        [("1", "onion"), ("2 cloves", "garlic"), ("1 thumb", "ginger"), ("1 tbsp", "vegetable oil"),
         ("3 tbsp", "mild curry paste"), ("4", "chicken thighs or breasts"), ("1 tin", "chopped tomatoes"),
         ("1 tin", "coconut milk"), ("1 handful", "spinach"), ("300 g", "basmati rice")],
        ["Chop the onion and grate the garlic and ginger.",
         "Cut the chicken into bite-sized pieces on a separate board, then wash the board, knife and your hands.",
         "Fry the onion in the oil for 8 minutes until soft and golden.",
         "Add the garlic, ginger and curry paste and stir for 1 minute until it smells amazing.",
         "Add the chicken and stir until coated, then pour in the tomatoes and coconut milk.",
         "Simmer for 20 minutes until the chicken is cooked all the way through, with no pink in the middle.",
         "Meanwhile, rinse the rice and cook it following the packet.",
         "Stir the spinach into the curry until it wilts, then serve with the rice."],
        "Use chickpeas and sweet potato instead of chicken for a veggie version.",
    ),
    _item(
        "recipe", "teen-victoria-sponge", "Victoria sponge", "🍰", "Baking", 60, "medium", 11, "8 slices",
        "The classic British cake. Two light sponges sandwiched with jam and cream.",
        [("200 g", "softened butter"), ("200 g", "caster sugar"), ("4", "eggs"), ("200 g", "self-raising flour"),
         ("1 tsp", "baking powder"), ("2 tbsp", "milk"), ("4 tbsp", "strawberry jam"), ("150 ml", "double cream"),
         ("", "icing sugar to dust")],
        ["Heat the oven to 190°C (170°C fan, gas 5). Grease and line two 20 cm cake tins.",
         "Beat the butter and sugar together until pale and fluffy.",
         "Beat in the eggs one at a time, adding a spoonful of flour with each to stop it curdling.",
         "Fold in the rest of the flour, the baking powder and the milk until smooth.",
         "Divide the mixture between the tins and level the tops.",
         "Bake for 20 to 25 minutes until golden and a skewer comes out clean.",
         "Cool for 10 minutes in the tins, then turn out onto a rack to cool completely.",
         "Whip the cream to soft peaks. Spread jam on one sponge, then cream, then add the other sponge on top and dust with icing sugar."],
        "Weigh your eggs in their shells and use the same weight of butter, sugar and flour for a perfect sponge every time.",
    ),
    _item(
        "recipe", "teen-bread-rolls", "Soft bread rolls", "🥖", "Baking", 120, "medium", 11, "8 rolls",
        "Proper homemade bread. Most of the time is waiting while it rises.",
        [("500 g", "strong white bread flour"), ("7 g sachet", "fast-action yeast"), ("1 tsp", "salt"),
         ("1 tbsp", "sugar"), ("300 ml", "warm milk"), ("30 g", "melted butter"), ("1", "egg for glazing")],
        ["Mix the flour, yeast, salt and sugar in a big bowl.",
         "Add the warm milk and melted butter and mix into a soft dough.",
         "Knead for 10 minutes until smooth and springy. Poke it: it should spring back.",
         "Cover and leave to rise for about an hour, until doubled.",
         "Knock it back and divide into 8 equal pieces. Weighing them gives even rolls.",
         "Shape each into a tight ball and space them out on a lined baking tray. Cover and rise for 30 minutes.",
         "Heat the oven to 200°C (180°C fan, gas 6). Brush the rolls with beaten egg.",
         "Bake for 15 to 18 minutes until golden. They should sound hollow when tapped underneath."],
    ),
    _item(
        "recipe", "teen-budget-dinner-challenge", "Family dinner on a budget", "💷", "Challenges", 90, "tricky", 13, "4 people",
        "Plan, shop for and cook a two-course dinner for four with a £10 budget. Real-life maths and cooking in one.",
        [("£10", "budget"), ("", "a notebook or spreadsheet"), ("", "supermarket website or trip"),
         ("", "store cupboard staples (oil, salt, pepper)")],
        ["Pick a main and a simple pudding. Look through the Cookbook for ideas.",
         "Check what's already in the cupboards and fridge so you don't buy it twice.",
         "Write a shopping list with prices from a supermarket website, and total it up.",
         "Over budget? Swap to cheaper brands, use seasonal veg, or change a recipe until you're under £10.",
         "Do the shop, with a grown-up or online, and keep the receipt.",
         "Write a timeline working back from dinner time, so everything is ready together.",
         "Cook the meal, then work out the cost per person.",
         "Ask the family for feedback. What would you change next time?"],
        "Great for a maths and life-skills lesson. Save the costings in your Journal.",
    ),
    _item(
        "recipe", "teen-fluffy-pancakes", "Fluffy American pancakes", "🥞", "Breakfast", 25, "easy", 10, "10 pancakes",
        "Thick, fluffy pancakes for a weekend breakfast. Perfect for practising flipping.",
        [("200 g", "self-raising flour"), ("1 tsp", "baking powder"), ("1 tbsp", "caster sugar"), ("2", "eggs"),
         ("250 ml", "milk"), ("", "butter for the pan"), ("", "fruit and maple syrup to serve")],
        ["Whisk the flour, baking powder and sugar together in a bowl.",
         "In a jug, beat the eggs with the milk.",
         "Pour the wet into the dry and whisk until just smooth. A few small lumps are fine.",
         "Heat a frying pan over a medium heat and add a little butter.",
         "Pour in small ladlefuls of batter. Cook until bubbles pop on top, about 1 to 2 minutes.",
         "Flip and cook for another minute until golden.",
         "Keep them warm in a low oven while you cook the rest, then serve with fruit and syrup."],
    ),
    _item(
        "recipe", "teen-burgers-wedges", "Homemade burgers and wedges", "🍔", "Dinners", 60, "medium", 12, "4 burgers",
        "Juicy homemade burgers with crispy oven wedges. Better and cheaper than a takeaway.",
        [("500 g", "beef mince"), ("1", "small onion"), ("1", "egg"), ("1 tsp", "mustard"),
         ("4", "burger buns"), ("4", "large potatoes"), ("2 tbsp", "olive oil"), ("1 tsp", "smoked paprika"),
         ("", "lettuce, tomato and cheese slices")],
        ["Heat the oven to 200°C (180°C fan, gas 6).",
         "Cut the potatoes into wedges, toss with oil, paprika and salt on a tray and roast for 40 minutes, turning halfway.",
         "Grate the onion and mix it with the mince, egg, mustard, salt and pepper.",
         "Shape into 4 flat burgers slightly wider than the buns. Press a dip in the middle so they stay flat.",
         "Wash your hands well after handling raw meat.",
         "Fry the burgers in a hot pan for 5 to 6 minutes each side, until cooked through with no pink in the middle.",
         "Toast the buns and build your burgers with salad and cheese."],
    ),
    _item(
        "recipe", "teen-brownies", "Gooey chocolate brownies", "🍫", "Baking", 45, "easy", 10, "16 squares",
        "Rich, fudgy brownies. A crowd-pleaser for any occasion.",
        [("185 g", "butter"), ("185 g", "dark chocolate"), ("275 g", "caster sugar"), ("3", "eggs"),
         ("85 g", "plain flour"), ("40 g", "cocoa powder"), ("100 g", "chocolate chips (optional)")],
        ["Heat the oven to 180°C (160°C fan, gas 4) and line a 20 cm square tin.",
         "Melt the butter and chocolate together in a bowl over a pan of simmering water, then let it cool a little.",
         "Whisk the eggs and sugar until pale and thick.",
         "Pour in the chocolate mixture and fold together.",
         "Sift in the flour and cocoa and fold gently. Stir in the chocolate chips.",
         "Pour into the tin and bake for 25 minutes. The middle should still wobble slightly.",
         "Leave to cool completely in the tin before cutting into squares."],
        "Underbaking is the secret to gooey brownies. They firm up as they cool.",
    ),
    _item(
        "recipe", "teen-fajitas", "Chicken fajitas", "🌯", "Dinners", 35, "easy", 11, "4 people",
        "Sizzling spiced chicken and peppers in soft wraps. Everyone builds their own.",
        [("3", "chicken breasts"), ("2", "peppers"), ("1", "red onion"), ("2 tbsp", "fajita seasoning"),
         ("1 tbsp", "vegetable oil"), ("8", "tortilla wraps"), ("", "salsa, soured cream and grated cheese")],
        ["Slice the peppers and onion into strips.",
         "On a separate board, slice the chicken into thin strips. Wash the board, knife and hands.",
         "Toss the chicken with the seasoning and a little oil.",
         "Fry the chicken in a hot pan for 6 to 8 minutes until cooked through, then tip onto a plate.",
         "Fry the peppers and onion in the same pan for 5 minutes until soft and charred at the edges.",
         "Put the chicken back in to warm through.",
         "Warm the wraps and serve everything at the table so everyone can build their own."],
    ),
    _item(
        "recipe", "teen-mac-and-cheese", "Mac and cheese from scratch", "🧀", "Dinners", 40, "medium", 11, "4 people",
        "Learn to make a proper cheese sauce: a skill you'll use in lasagne, fish pie and more.",
        [("300 g", "macaroni"), ("50 g", "butter"), ("50 g", "plain flour"), ("600 ml", "milk"),
         ("200 g", "mature cheddar"), ("1 tsp", "mustard"), ("2 tbsp", "breadcrumbs")],
        ["Heat the oven to 200°C (180°C fan, gas 6).",
         "Cook the macaroni for 2 minutes less than the packet says, then drain.",
         "Melt the butter in a saucepan, stir in the flour and cook for 1 minute to make a paste (a roux).",
         "Take the pan off the heat and whisk in the milk a little at a time until smooth.",
         "Put it back on the heat and keep stirring until it thickens and bubbles.",
         "Stir in most of the cheese and the mustard until melted.",
         "Mix in the pasta, tip into an ovenproof dish and top with the rest of the cheese and the breadcrumbs.",
         "Bake for 20 minutes until golden and bubbling."],
    ),
]

TEEN_CRAFTS = [
    _item(
        "craft", "teen-lino-printing", "Lino printing", "🖨️", "Printmaking", 120, "medium", 12, None,
        "Carve your own design into lino and print it on cards, paper or fabric.",
        [("1", "soft-cut lino block"), ("1", "lino cutting tool set"), ("1", "ink roller (brayer)"),
         ("1 tube", "water-based block printing ink"), ("", "pencil and tracing paper"), ("", "paper or blank cards")],
        ["Draw a simple, bold design. Remember it will print in reverse, so flip any letters.",
         "Trace or draw it onto the lino block.",
         "Carve away everything you don't want to print. Always cut away from your body and keep your other hand behind the blade.",
         "Squeeze a little ink onto a tray and roll it out until it looks like velvet.",
         "Roll ink evenly over the block.",
         "Lay your paper on top and rub firmly all over with the back of a spoon.",
         "Peel the paper off slowly to reveal your print, then leave it to dry."],
        "Soft-cut lino is much easier and safer to carve than traditional lino. A bench hook stops the block slipping.",
    ),
    _item(
        "craft", "teen-embroidery-hoop", "Embroidery hoop art", "🧵", "Textiles", 90, "easy", 10, None,
        "Stitch a design in a hoop to hang on your wall. Learn backstitch, satin stitch and French knots.",
        [("1", "embroidery hoop (15 cm)"), ("1 piece", "cotton or calico fabric"), ("", "embroidery threads"),
         ("1", "embroidery needle"), ("", "water-soluble pen or pencil"), ("", "small scissors")],
        ["Put the fabric in the hoop and tighten it until it's as tight as a drum.",
         "Draw your design lightly on the fabric: a plant, your initials or a simple animal work well.",
         "Split the thread into 2 or 3 strands and knot the end.",
         "Outline your design with backstitch: come up, go back one stitch, come up one stitch ahead.",
         "Fill shapes with satin stitch: straight stitches laid side by side.",
         "Add dots with French knots: wrap the thread twice round the needle and go back in next to where you came out.",
         "Trim the fabric round the back of the hoop and hang it up."],
    ),
    _item(
        "craft", "teen-macrame-hanger", "Macramé plant hanger", "🪴", "Knotting", 90, "medium", 11, None,
        "Knot a plant hanger with just cord and a ring. Perfect for a bedroom plant.",
        [("20 m", "macramé cord (4–5 mm)"), ("1", "wooden or metal ring"), ("1", "small plant pot"), ("", "scissors"),
         ("", "tape measure")],
        ["Cut 8 pieces of cord, each 2.5 m long.",
         "Thread them through the ring and fold in half, so you have 16 strands. Tie them together under the ring.",
         "Split the strands into 4 groups of 4.",
         "In each group, tie 6 square knots in a column.",
         "Drop down 10 cm and tie each group's strands to the neighbouring group with a square knot, making a net.",
         "Drop down another 8 cm and repeat, which forms the basket.",
         "Gather all the strands together below and tie a wrapping knot. Trim the tassel.",
         "Pop the pot in and hang it up."],
        "Look up \"macramé square knot\" if you're stuck. It's the same knot repeated all the way down.",
    ),
    _item(
        "craft", "teen-tshirt-tote", "No-sew T-shirt tote bag", "👜", "Upcycling", 30, "easy", 10, None,
        "Turn an old T-shirt into a reusable shopping bag without a single stitch.",
        [("1", "old T-shirt"), ("", "sharp fabric scissors"), ("", "a ruler and chalk")],
        ["Turn the T-shirt inside out and lay it flat.",
         "Cut off the sleeves just inside the seams.",
         "Cut a scoop out of the neckline to make the bag opening and handles.",
         "Cut the bottom hem off, then cut strips 8 cm long and 2 cm apart through both layers along the bottom.",
         "Tie each front strip to the back strip below it in a double knot.",
         "Tie neighbouring knots together to close any gaps.",
         "Turn it right side out and take it shopping!"],
    ),
    _item(
        "craft", "teen-birdhouse", "Wooden birdhouse", "🏠", "Woodwork", 180, "tricky", 12, None,
        "Build a real nest box for garden birds from one plank of wood.",
        [("1", "untreated plank (15 cm × 1.5 cm × 1.2 m)"), ("", "saw"), ("", "hand drill with 25–32 mm hole saw"),
         ("", "hammer and 30 mm nails or screws"), ("", "sandpaper"), ("", "pencil and ruler")],
        ["Mark out the pieces: front 20 cm, back 30 cm, two sides 25 cm, base 11 cm and roof 20 cm.",
         ("Cut the pieces with the saw, with the wood held firmly in a vice or clamp.", G),
         ("Drill the entrance hole in the front, about 12 cm up from the bottom.", G),
         "Sand all the edges smooth.",
         "Nail the sides to the base, then the front and back.",
         "Fix the roof on with a strip of old rubber or leather as a hinge, so it can be cleaned out.",
         "Drill two small drainage holes in the base.",
         "Fix it 2 to 4 m up a tree or wall, facing north-east, away from strong sun and wind."],
        "Don't paint the inside or add a perch, as both can harm the birds. A 25 mm hole suits blue tits, 32 mm suits sparrows.",
    ),
    _item(
        "craft", "teen-zine", "Make a zine", "📰", "Paper", 60, "easy", 11, None,
        "A mini magazine folded from a single sheet of paper. Write, draw and photocopy your own.",
        [("1", "A4 sheet of paper"), ("", "scissors"), ("", "pens, collage scraps and glue")],
        ["Fold the paper in half lengthways, then widthways twice, so you have 8 panels.",
         "Unfold it, then fold in half widthways.",
         "Cut along the middle fold from the folded edge to the centre only.",
         "Open it up, fold lengthways again and push the ends together so the slit opens into a little book.",
         "Fold it flat into an 8-page booklet.",
         "Plan your theme: a comic, a guide to your favourite hobby, poems or a local nature report.",
         "Fill every page with words, drawings and collage.",
         "Unfold it and photocopy it to share with friends and family."],
    ),
    _item(
        "craft", "teen-bullet-journal", "Bullet journal set-up", "📓", "Planning", 60, "easy", 11, None,
        "Design your own planner to track tasks, habits and goals. Brilliant for independent learning.",
        [("1", "dotted notebook"), ("", "a black fine-liner"), ("", "coloured pens or highlighters"), ("", "a ruler")],
        ["Number the pages and make an index on the first two pages.",
         "Draw a future log: the next 6 months on two pages, for birthdays and big dates.",
         "Set up this month: a calendar down one side and a task list on the other.",
         "Add a habit tracker: a grid with habits down the side and days across the top.",
         "Start a daily log: write the date, then tasks (•), events (○) and notes (–).",
         "At the end of each day, tick finished tasks and move unfinished ones forward (>).",
         "Add a collection page for anything else, like books to read or learning goals."],
        "Keep it simple at first. The best journal is the one you actually use.",
    ),
    _item(
        "craft", "teen-sewing-repairs", "Sewing repairs: buttons and hems", "🪡", "Life skills", 45, "easy", 10, None,
        "Two repairs everyone should know. Save clothes from the bin and save money.",
        [("1", "needle"), ("", "thread to match the fabric"), ("", "spare button"), ("", "pins"), ("", "small scissors")],
        ["Button: thread the needle and double the thread over, then knot the ends.",
         "Put the button where the old one was and come up through one hole from the back.",
         "Go down through the opposite hole. Repeat 6 to 8 times through each pair of holes.",
         "Wind the thread round the stitches under the button a few times, then knot it at the back.",
         "Hem: fold the fallen hem back up to match the rest, and pin it.",
         "Use slip stitch: pick up one or two threads of the outer fabric, then slide the needle along inside the fold.",
         "Keep stitches small and even, then knot securely at the end."],
    ),
    _item(
        "craft", "teen-stop-motion", "Stop-motion film", "🎬", "Digital", 120, "medium", 11, None,
        "Make a short animated film with a phone or tablet, using clay figures, LEGO or paper cut-outs.",
        [("1", "phone or tablet with a free stop-motion app"), ("", "a stand or pile of books to hold it still"),
         ("", "modelling clay, LEGO or paper characters"), ("", "a lamp")],
        ["Plan a 10 to 20 second story with a clear start, middle and end. Sketch a quick storyboard.",
         "Build your characters and a simple set.",
         "Fix the phone so it can't move, and use a lamp rather than daylight so the light stays the same.",
         "Take a photo, move the characters a tiny amount, take another photo. Repeat!",
         "Aim for about 12 photos for every second of film.",
         "Play it back as you go to check the movement looks smooth.",
         "Add titles, music or sound effects in the app, then share your premiere with the family."],
    ),
    _item(
        "craft", "teen-tie-dye", "Tie-dye T-shirt", "🌀", "Textiles", 60, "medium", 10, None,
        "Twist, tie and dye a T-shirt with bold spirals. Best done outside!",
        [("1", "white cotton T-shirt"), ("1", "tie-dye kit with squeezy bottles"), ("", "elastic bands"),
         ("", "rubber gloves"), ("", "plastic bags and an old tablecloth")],
        ["Wash the T-shirt first and leave it damp.",
         "Pinch the centre and twist it round and round into a flat spiral.",
         "Wrap 3 or 4 elastic bands across the spiral so it looks like a pie cut into slices.",
         "With gloves on, squirt a different colour onto each slice, on both sides.",
         "Wrap it in a plastic bag and leave for 8 to 24 hours.",
         "Rinse under cold water until it runs clear, then take the bands off.",
         "Wash it on its own the first time."],
        "Cover everything nearby. Dye stains skin, clothes and tables.",
    ),
    _item(
        "craft", "teen-friendship-bracelets", "Friendship bracelets", "🧶", "Knotting", 45, "easy", 10, None,
        "Knot colourful chevron bracelets to keep or give away.",
        [("", "embroidery threads in 4 colours"), ("", "sticky tape or a safety pin"), ("", "scissors")],
        ["Cut two 80 cm lengths of each colour, so you have 8 strands.",
         "Knot them together at the top and tape the knot to a table.",
         "Arrange the colours in a mirror image: A B C D D C B A.",
         "Take the left strand and tie forward knots over each strand until you reach the middle.",
         "Take the right strand and tie backward knots towards the middle.",
         "Knot the two middle strands together. That completes one row of the V.",
         "Repeat until the bracelet fits round your wrist, then knot the end and plait the tails to tie it on."],
    ),
    _item(
        "craft", "teen-clay-trinket-dish", "Air-dry clay trinket dish", "🏺", "Modelling", 60, "easy", 10, None,
        "Shape and paint a little dish for jewellery or keys. No kiln needed.",
        [("250 g", "air-dry clay"), ("", "rolling pin"), ("", "a small bowl as a mould"), ("", "acrylic paint"),
         ("", "PVA or varnish"), ("", "sandpaper")],
        ["Roll the clay out to about 5 mm thick.",
         "Cut out a circle or leaf shape, or press in a pattern with lace or leaves.",
         "Press it gently into a small bowl to curve the edges, and smooth any cracks with a wet finger.",
         "Leave it to dry for 24 to 48 hours.",
         "Sand any rough edges.",
         "Paint your design and let it dry.",
         "Seal it with varnish or a coat of PVA."],
    ),
]
