"""Little Roots: short, playful activities for 3 and 4 year olds, done by a grown-up with the child.
Written for Bright Roots.

The category is the area of learning. The areas loosely follow Realising the Ambition (Scotland) and
the EYFS: Talk, Early maths, Letters and sounds, Moving, Creating and The world around us. The words
are our own; only the headings are borrowed.
"""
from make_starters import _item

TALK = "Talk"
MATHS = "Early maths"
SOUNDS = "Letters and sounds"
MOVING = "Moving"
CREATING = "Creating"
WORLD = "The world around us"


def _little(slug, title, emoji, category, minutes, summary, materials, steps, talk, more, easier, safety, story):
    """`story` is read aloud in the story book: an opening, one line for each step, then an ending."""
    assert len(story) == len(steps) + 2, slug
    data = _item("little", slug, title, emoji, category, minutes, "easy", 3, None, summary, materials, steps, safety)
    data.update({"talk": talk, "more": more, "easier": easier, "story": story})
    return data


LITTLE_ROOTS = [
    _little(
        "little-teddys-tea-party", "Teddy's tea party", "🍪", MATHS, 15,
        "Lay a tea party for the soft toys and share things out: one for you, one for you.",
        [("3", "soft toys"), ("3", "plastic cups or bowls"), ("3", "spoons"),
         ("a small tub of", "dry cereal pieces or crackers broken into bits"), ("1", "tea towel for a tablecloth")],
        ["Spread the tea towel on the floor and sit the toys round it. Let your child choose who is coming.",
         "Ask them to give each guest one cup, then one spoon each.",
         "Share out the snack: \"one for Teddy, one for Bunny, one for Duck\", then round again.",
         "Count each guest's pile together, touching each piece as you count.",
         "Make a mistake on purpose (\"Oh no, Duck has none!\") and let them fix it."],
        ["How many friends are at the party?",
         "Does everyone have a cup? How do you know?",
         "Who has more? Who has fewer? How can we make it fair?"],
        "A surprise guest arrives: \"Now there are 4 friends. Do we need more cups?\" Or count to 5 for each guest.",
        "Just lay the table together and say \"one each\" as you go. That's the whole skill.",
        "Stay with them while there's food out. No whole nuts, popcorn, whole grapes or hard sweets for under 5s. "
        "Check for allergies if anyone else joins in.",
        ["It was a sunny morning, and Teddy had a big idea. \"Let's have a tea party!\" he said. \"But who will help me get ready?\"",
         "Teddy needs a tablecloth and some friends. Who is coming to the party today?",
         "Everybody needs a cup and a spoon. One for Teddy, one for Bunny, one for Duck. Has everyone got one?",
         "Snack time! Teddy shares them out very carefully, so nobody is left out.",
         "Teddy counts his snacks: one, two, three. How many have his friends got?",
         "Oh no! Duck looks sad. Duck hasn't got any! Can you help Teddy make it fair?",
         "Everybody had the same, and everybody was happy. \"Thank you for helping,\" said Teddy. \"That was the best tea party ever!\""],
    ),
    _little(
        "little-mystery-bag", "The mystery bag", "🎁", SOUNDS, 10,
        "Feel a hidden object, guess what it is, then hear the sound its name starts with.",
        [("1", "pillowcase or cloth bag"),
         ("5", "familiar things that start with a clear sound, e.g. a sock, spoon, teddy, cup and brush")],
        ["Without them looking, put the objects in the bag.",
         "Let them put a hand in, feel one thing and guess before pulling it out.",
         "When it comes out, say its name slowly and stretch the first sound: \"sssss-ock\".",
         "Ask them to say it with you, then put it in a line on the floor.",
         "At the end, point along the line and say each one together."],
        ["What can you feel? Is it soft or hard? Bumpy or smooth?",
         "What do you think it is?",
         "Listen: sssss-ock. What sound does sock start with?"],
        "Ask them to find something else in the room that starts with the same sound (\"s, s, sofa!\"). "
        "Or let them fill the bag for you to guess.",
        "Skip the sounds. Just feel, guess and name. Describing words count as learning too.",
        "Only use things bigger than a toilet roll tube is wide, so nothing can be swallowed. No coins, button "
        "batteries, magnets, balloons or anything sharp. Keep the bag out of reach afterwards and don't let them "
        "put it over their head.",
        ["Deep in the cupboard lived a magic bag. Nobody knew what was inside it. Shall we find out?",
         "Shh! Close your eyes. The magic bag is filling up with surprises.",
         "Put your hand in, slowly, slowly. What can you feel? Is it soft? Is it bumpy?",
         "Out it comes! Let's say its name slowly, like a snake: sssss-ock!",
         "Say it with me! Then put it in the line, all in a row.",
         "Look at everything the magic bag gave us! Let's say them all together.",
         "The magic bag is empty now. \"Thank you for playing,\" it whispered. \"Fill me up again another day!\""],
    ),
    _little(
        "little-animal-moves", "Animal moves", "🐱", MOVING, 15,
        "Hop like a frog, waddle like a penguin and freeze like a statue when the music stops.",
        [("", "a clear space indoors or outside"), ("", "music on a phone (optional)")],
        ["Clear a space together and check the floor. Bare feet are best on a slippy floor.",
         "Take turns choosing an animal and moving like it. Frog: crouch and jump forwards. Bear: walk on hands "
         "and feet. Flamingo: stand on one leg and count to 3. Snake: slither on your tummy. Penguin: feet "
         "together, tiny waddling steps.",
         "Play Freeze: move like an animal while the music plays or while you sing. When it stops, everyone "
         "freezes like a statue.",
         "Finish lying down as a sleepy cat, breathing slowly while you count to 5 together."],
        ["Can you be a big frog? Now a tiny frog?",
         "Which animal is fastest? Which is slowest?",
         "Can you be a flamingo for longer than me?"],
        "Make a little obstacle path: hop like a frog to the cushion, crawl like a bear under the table, waddle "
        "back. Or let them invent an animal and teach you its move.",
        "Just play Freeze with any wiggly dancing. Stopping on a signal is the skill.",
        "Move furniture with sharp corners out of the way, and keep away from stairs, fireplaces and open doors. "
        "Bare feet or grippy socks, not plain socks on hard floors. Under the table only if it's sturdy.",
        ["Far away in the jungle, the animals were having a party. Everyone was invited, even you!",
         "The animals need lots of room to play. Is the floor all clear? Off we go!",
         "Can you hop like a frog? Stomp like a bear? Stand on one leg like a flamingo?",
         "When the music stops... freeze! Don't move a whisker!",
         "All that dancing made the animals sleepy. Curl up like a cat and breathe slowly, in and out.",
         "Shh, the jungle is quiet now. Every animal had a wonderful time. Goodnight, little animals!"],
    ),
    _little(
        "little-rainbow-hunt", "Rainbow hunt", "🌈", MATHS, 15,
        "Hunt round the house for things of each colour, then sort them into colour piles.",
        [("4", "bowls, trays or sheets of paper in red, yellow, green and blue"), ("1", "basket or bag for collecting")],
        ["Put out the bowls or paper and name each colour together.",
         "Choose a colour and hunt round the room for things that colour. Bring back one or two each time.",
         "Drop each thing into the bowl that matches. Ask: \"Does it go here?\"",
         "When a bowl has a few things in it, count them together, touching each one.",
         "Look at all the piles. Which has the most? Which has the fewest?"],
        ["What colour is this? Can you find something else the same?",
         "Which pile is the biggest? How do you know?",
         "This one is two colours! Where shall it go?"],
        "Add more colours (orange, purple, pink), or sort everything again a new way: big and small, soft and hard.",
        "Hunt for just one colour, and say its name every time you find one.",
        "Keep the hunt to one or two rooms you have checked. Leave out small things that could be swallowed, "
        "medicines, cleaning products and anything with button batteries.",
        ["Oh dear! The rainbow had lost all its colours. \"Can you help me find them?\" it asked.",
         "Here are the rainbow's colour pots: red, yellow, green and blue. Can you say them with me?",
         "The colours are hiding all round the house! Let's go and look. What can you find?",
         "Pop each one in the right pot. Red with red, blue with blue.",
         "Let's count what we found. One, two, three...",
         "Look at all those colours! Which pot is the fullest?",
         "The rainbow shone brighter than ever. \"Thank you!\" it said. \"Now I'm the most colourful rainbow in the sky.\""],
    ),
    _little(
        "little-box-castle", "Box castle", "🏰", MATHS, 15,
        "Build a castle from empty boxes and talk about tall, short, big and small.",
        [("6 to 10", "empty boxes, tubes and tubs of different sizes"), ("1", "small toy to live in the castle")],
        ["Tip the boxes out and look at them together. Which is the biggest? Which is the smallest?",
         "Start the castle with a big box at the bottom. Ask them which box should go next.",
         "Build a tower as tall as you can, counting the boxes as you add them.",
         "When it falls (it will!), laugh and build it again. Try the big boxes at the bottom this time.",
         "Pop the toy inside or on top. Is the castle taller than the toy? Taller than your child?"],
        ["Which box is bigger? Which is smaller?",
         "Why do you think the tower fell down?",
         "How many boxes tall is our castle?"],
        "Look at the shapes: which boxes have flat sides and which ones roll? Or try building two towers the same height.",
        "Just stack and knock down. Say \"up, up, up\" and \"crash!\" together.",
        "Take off plastic film, staples and tape first, and check tubes for sharp edges. Build somewhere a falling "
        "tower can't knock anything else over.",
        ["Pip and her little dog needed a new home. \"Can you build us a castle?\" asked Pip.",
         "Look at all the building blocks! Which one is the biggest? Which one is tiny?",
         "Every castle needs strong walls at the bottom. Which box shall we start with?",
         "Up, up, up the castle goes! Let's count the boxes. How tall can it grow?",
         "Crash! Oh no, the castle fell down! Never mind. Let's build it again, even stronger.",
         "Pip moves into the castle. Is it taller than Pip? Is it taller than you?",
         "\"It's perfect!\" said Pip, waving from the very top. \"Thank you for building the best castle in the land.\""],
    ),
    _little(
        "little-little-shop", "Little shop", "🛒", TALK, 15,
        "Set up a pretend shop with things from the kitchen and take turns being the shopkeeper.",
        [("5 to 8", "tins, packets and fruit from the kitchen"), ("1", "bag or basket"),
         ("a few", "pieces of paper money you draw and cut out together")],
        ["Set the shop out on a low table or a box. Let your child choose what to sell.",
         "You be the shopper first. Say hello, ask for one thing, and say please and thank you.",
         "Swap over: now they're the shopper. Give them a bag and some paper money.",
         "Ask them to buy two things, then three. Can they remember them all?",
         "Close the shop together and put everything back in the cupboard."],
        ["Good morning! What would you like today?",
         "What does the apple feel like? What colour is it?",
         "What else could our shop sell?"],
        "Draw a picture shopping list together, or give each thing a price of 1, 2 or 3 pennies and count out the money.",
        "Just take turns handing things over and saying \"Here you are\" and \"Thank you\".",
        "Use paper money, not real coins, which are a choking risk. Leave out glass jars, tins with sharp edges "
        "and anything someone is allergic to.",
        ["Mrs Mouse was opening a brand new shop. \"I need a helper,\" she squeaked. \"Will you help me?\"",
         "Let's fill the shelves! What shall we sell in our shop?",
         "Ding-a-ling! Here comes the first shopper. Hello! What would you like?",
         "Now it's your turn to go shopping. Don't forget your bag and your money!",
         "Can you remember everything on your list? One, two, three things.",
         "Time to close the shop. Let's tidy everything away.",
         "\"What a busy day!\" said Mrs Mouse. \"You were the best shop helper ever. Come back tomorrow!\""],
    ),
    _little(
        "little-story-basket", "Story basket", "📖", TALK, 10,
        "Pull three things out of a basket and make up a story about them together.",
        [("1", "basket, box or bag"), ("3", "everyday things, e.g. a toy animal, a hat and a wooden spoon")],
        ["Put three things in the basket without them looking.",
         "Pull out the first one and start the story: \"Once upon a time, there was a...\"",
         "Pull out the next thing and ask how it gets into the story. Say yes to every idea.",
         "Pull out the last thing and ask: \"And then what happened?\"",
         "Finish together with \"...and they all lived happily ever after. The end!\" Then tell the whole story back."],
        ["Once upon a time, there was a...",
         "What happened next?",
         "How do you think they felt?"],
        "Act the story out with the things, or let your child fill the basket and start the story for you.",
        "Pull out one thing at a time and just talk about it: what is it, what does it do, who might use it?",
        "Choose things bigger than a toilet roll tube is wide. No keys, coins, batteries or anything sharp.",
        ["Once upon a time there was a basket that loved stories. But it didn't have any! \"Will you make one for me?\" it asked.",
         "Shh, the story basket is getting ready. What could be inside?",
         "Here's the first thing! Every story starts with \"Once upon a time...\"",
         "What's this? How does it get into our story?",
         "And then what happened? You decide!",
         "...and they all lived happily ever after. The end!",
         "The story basket was so happy. \"That's my favourite story ever,\" it said. \"Will you tell me another one tomorrow?\""],
    ),
    _little(
        "little-whos-that-sound", "Who's that sound?", "🦁", SOUNDS, 10,
        "Guess the animal from its noise, then play with loud, quiet, high and low sounds.",
        [("4 or 5", "toy animals or animal pictures, e.g. a lion, cow, cat, dog and duck"),
         ("1", "cushion or blanket to hide behind")],
        ["Look at the animals together and make each one's noise.",
         "Hide behind the cushion with one animal and make its noise. Can they guess who it is?",
         "Swap over: they hide an animal and make the noise for you to guess.",
         "Make the sounds loud like a big lion, then quiet like a tiny lion. High like a mouse, low like a cow.",
         "End with all the animals going to sleep: the quietest sound you can make."],
        ["Who do you think is hiding?",
         "Can you roar loudly? Now very quietly?",
         "Which animal makes the highest sound? The lowest?"],
        "Shut your eyes and listen to sounds around the house: a tap running, a door closing, a spoon in a cup. "
        "What made that sound?",
        "Just make the animal noises together and point to the right animal.",
        "Keep small toy animals away from babies and toddlers. Gentle sounds near little ears: no shouting right "
        "next to them.",
        ["Down on the farm, the animals (and a lion who came to visit!) were playing hide and seek. But they kept making noises!",
         "Let's meet the animals. What sound does each one make?",
         "Someone is hiding behind the haystack. Listen... who can it be?",
         "Your turn to hide! Make your animal's noise. Can I guess?",
         "The big lion roars loudly. The tiny lion roars quietly. Can you do both?",
         "It's getting late, and the animals are sleepy. Shhh, can you make a very quiet sound?",
         "All the animals were fast asleep. \"Goodnight, farm,\" whispered the moon. \"You were all very good listeners.\""],
    ),
    _little(
        "little-rocket-blast-off", "Rocket blast off", "🚀", MOVING, 10,
        "Count down from 5, crouch low and blast off with a big jump, then land softly on the moon.",
        [("", "a clear space"), ("2 or 3", "cushions for landing pads"),
         ("1", "big box or chair to be the rocket (optional)")],
        ["Clear a space and put the cushions down as landing pads on the moon.",
         "Climb into the rocket, or stand beside it. Put on your pretend space helmets.",
         "Crouch down low and count down together: 5, 4, 3, 2, 1... blast off! Jump up as high as you can.",
         "Fly round the room with your arms out, then land gently on a cushion with soft, bendy knees.",
         "Walk on the moon with big slow steps, then fly home and lie as still as a star."],
        ["Can you count down with me? 5, 4, 3, 2, 1...",
         "How high can you jump?",
         "What do you think is on the moon?"],
        "Count down from 10. Or land on one leg, or tiptoe slowly as if you're floating in space.",
        "Just count down and jump together, as many times as they like.",
        "Move sharp corners out of the way and keep away from stairs and windows. Cushions on carpet, not on a "
        "slippy floor where they can slide. Jump from the floor, never off furniture.",
        ["Captain Star had a very important job. She was flying to the moon! But she needed a crew. Will you come?",
         "First we get the moon ready. Where shall the landing pads go?",
         "Into the rocket! Helmets on. Seat belts on. Ready?",
         "Get down low... 5, 4, 3, 2, 1... BLAST OFF!",
         "Whoosh! We're flying through space. Now land gently on the moon.",
         "Big, slow moon steps. Then home we go, lying still as a star.",
         "\"Mission complete!\" said Captain Star. \"You were the best crew in the whole galaxy.\""],
    ),
    _little(
        "little-water-painting", "Water painting", "🎨", CREATING, 15,
        "Paint walls, fences and paths outside with just water and a big brush, and watch the pictures disappear.",
        [("1", "bucket or tub with a little water in it"), ("2", "big paintbrushes or decorating brushes, or a sponge"),
         ("", "a wall, fence, path or step outside")],
        ["Put a little water in the bucket (not too much) and take it outside.",
         "Show them how to dip the brush and paint the wall. Big sweeps up and down, then round and round.",
         "Paint lines, circles and zigzags. Try the first letter of their name.",
         "Watch what happens: where does the painting go? Try painting in a sunny spot and a shady spot.",
         "Pour the last of the water on a plant and bring everything in."],
        ["What happens to the water on the wall?",
         "Can you paint a big circle? A tiny one?",
         "Where did your picture go?"],
        "Paint a shape and ask them to paint over it exactly. Or draw with chalk and wash it away with the brush.",
        "Just splash, sweep and paint. Big arm movements are the skill, and they get hands ready for writing later.",
        "Stay with them near water, even a small bucket, and tip it out when you finish. Watch for slippy wet paving.",
        ["Little Snail wanted to paint a picture, but she didn't have any paint. \"I know!\" she said. \"I'll use magic water!\"",
         "Fill the bucket with magic water. Not too much!",
         "Dip, dip, swish! Big strokes, up and down, round and round.",
         "Can you paint a line? A circle? A zigzag like lightning?",
         "Look! The picture is disappearing! Where did it go?",
         "The plants are thirsty too. Let's give them the last drops.",
         "\"The sun drank up my pictures,\" laughed Little Snail. \"Now I can paint new ones every day!\""],
    ),
    _little(
        "little-leaf-faces", "Leaf faces", "🌳", CREATING, 15,
        "Collect leaves, sticks and seeds on a walk, then use them to make a face on the ground.",
        [("1", "bag or basket for collecting"), ("", "fallen leaves, small sticks, seeds and petals"),
         ("1", "tray or piece of cardboard (optional)")],
        ["Go for a short walk to the park or garden and collect fallen leaves, small sticks and seeds.",
         "Look at what you found. Sort it into big and small, or by colour.",
         "On the ground or a tray, start a face with a big leaf for the head.",
         "Add eyes, a nose, a mouth and hair. Let them choose where each bit goes.",
         "Take a photo of your leaf face, then leave the leaves outside for the minibeasts."],
        ["What colours are the leaves? Which one is the biggest?",
         "What can we use for the eyes?",
         "Is our face happy or sad? How could we change it?"],
        "Make a whole leaf animal, like a hedgehog or a bird. Or tell a story about who your leaf person is.",
        "Just collect, look and crunch the leaves. Naming colours and sizes is plenty.",
        "Only pick up fallen things and don't pull at plants. Leave mushrooms, berries and seeds you don't know, and "
        "nothing goes in mouths. Wash hands afterwards.",
        ["Down in the woods, the trees were dropping their leaves. \"Who will play with us?\" whispered the leaves.",
         "Let's go on a leaf hunt! What can you find on the ground?",
         "Look at all this treasure! Big and small, red, yellow and brown.",
         "Every face needs a head. Which leaf shall we use?",
         "Eyes, nose, mouth and hair. Hello, leaf friend!",
         "Say cheese! Now the leaves can go back to the minibeasts.",
         "The leaf friend smiled up at the sky. \"Thank you for making me,\" it rustled. \"See you next autumn!\""],
    ),
    _little(
        "little-minibeast-hunt", "Minibeast hunt", "🐝", WORLD, 15,
        "Look under logs and leaves for minibeasts, count their legs and put their homes back gently.",
        [("1", "magnifying glass (optional)"), ("", "a garden, park or path with logs, stones and leaves")],
        ["Head outside and talk about where minibeasts like to hide: dark, damp places.",
         "Gently lift a log, a stone or a pile of leaves together. Look closely. Who lives here?",
         "Watch a minibeast. Is it fast or slow? How many legs has it got? Does it have wings?",
         "Say goodbye and put everything back exactly as you found it, so the minibeasts keep their homes.",
         "Wash hands when you get in, and talk about who you met."],
        ["Where do you think a worm lives?",
         "How many legs does it have? Shall we count?",
         "Is it fast or slow? Big or small?"],
        "Draw your favourite minibeast, or build a bug hotel from sticks and leaves in a corner of the garden.",
        "Just look for one kind, like snails, and count how many you can find.",
        "Look, don't hold: let a minibeast walk onto a leaf rather than picking it up. Stay away from bees and wasps. "
        "Put every log and stone back, and wash hands afterwards.",
        ["Beatrice Bee was buzzing round the garden. \"My friends are hiding,\" she said. \"Can you help me find them?\"",
         "Where do little creatures hide? Somewhere dark and damp, I think!",
         "Lift the log very gently... who is under there?",
         "Look closely. A wiggly worm? A slow snail? A busy beetle? Let's count their legs.",
         "Shh, put their roof back gently. Everyone needs a home.",
         "Wash, wash, wash those hands. Who did we meet today?",
         "\"You found all my friends!\" buzzed Beatrice. \"Thank you for being so gentle with them.\""],
    ),
    _little(
        "little-shadow-play", "Shadow play", "🌙", WORLD, 10,
        "Make shadows with a torch in a dark room: big ones, small ones and a shadow puppet show.",
        [("1", "torch or phone torch"), ("", "a plain wall or a sheet"),
         ("2 or 3", "toys to make shadows with (optional)")],
        ["Make the room dark (close the curtains, or wait till evening) and switch on the torch.",
         "Shine the torch at the wall and hold your hand in front. Look, a shadow!",
         "Move your hand close to the torch, then far away. What happens to the shadow?",
         "Make shapes: a flapping bird, a dog, a rabbit with two fingers up. Let them try.",
         "Put on a little show with a toy's shadow, then switch the lights back on."],
        ["Where did the shadow come from?",
         "How can we make the shadow bigger? Smaller?",
         "What shape is your shadow? What could it be?"],
        "Go outside on a sunny day and find your shadow. Can you jump on it? Can you run away from it?",
        "Just wave your hands in the torch light and watch the shadows dance.",
        "Don't shine the torch in anyone's eyes, and keep a phone torch in your hand, not theirs. Clear the floor "
        "first so nobody trips in the dark.",
        ["When it got dark, Little Owl woke up. \"Hoo hoo! I want to play,\" she said. \"Let's play with shadows!\"",
         "Curtains closed. Lights off. Torch on! Are you ready?",
         "Look on the wall! Wave hello to your shadow.",
         "Closer to the torch... the shadow grows BIG! Far away... now it's tiny!",
         "Flap, flap, it's a bird! Can you make a rabbit too?",
         "Time for the shadow show! Then lights on, and the shadows run away.",
         "\"What a wonderful night,\" yawned Little Owl. \"Goodnight, shadows. See you next time it gets dark!\""],
    ),
]
