"""Outdoors: nature and adventure activities every family starts with, for ages 5 to 16. Written for Bright Roots.

Grouped by age so younger children get bug trails and older ones get maps, compasses and real skills.
Kept in sync on start-up by slug, like the recipes, crafts and P.E. ideas.
"""
from make_starters import G, _item

LITTLE = "Little explorers (5+)"
JUNIOR = "Adventurers (8+)"
TEEN = "Wild skills (11+)"

OUTDOOR = [
    # ---------- ages 5+ ----------
    _item(
        "outdoor", "out-bug-trail", "Bug trail", "🐞", LITTLE, 30, "easy", 5, "1 or more",
        "Hunt for minibeasts under logs, in leaves and on plants, and tick them off a spotter sheet.",
        [("1", "magnifying glass"), ("1", "pot or jar with holes in the lid"), ("1", "spotter sheet or notebook"),
         ("1", "soft paintbrush for moving bugs gently")],
        ["Make a spotter list together: ladybird, woodlouse, worm, spider, snail, beetle, ant, centipede.",
         "Look under stones and logs, in leaf piles and on the backs of leaves.",
         "Use the paintbrush to move a bug gently into the pot for a closer look.",
         "Count its legs and look at its body with the magnifying glass.",
         "Tick it off, then put it back exactly where you found it and roll the log back."],
        "Count legs to sort them: 6 legs is an insect, 8 is a spider, lots is a centipede or millipede.",
    ),
    _item(
        "outdoor", "out-bug-hotel", "Build a bug hotel", "🏨", LITTLE, 60, "easy", 5, "1 or more",
        "Stack natural bits and bobs into a cosy home for minibeasts, then check who's moved in.",
        [("", "an old crate, bricks or plant pots"), ("", "sticks, pine cones, straw, bark and dry leaves"),
         ("", "hollow stems or bamboo canes")],
        ["Pick a quiet, shady spot near plants.",
         "Build a frame from the crate, bricks or pots.",
         "Pack the gaps with sticks, cones, leaves, straw and hollow stems.",
         ("Cut bamboo canes to short lengths for bees to nest in.", G),
         "Check it every week and draw who you find."],
    ),
    _item(
        "outdoor", "out-leaf-rubbings", "Leaf and bark rubbings", "🍂", LITTLE, 30, "easy", 5, "1 or more",
        "Collect leaves and rub over them and tree bark with crayons to reveal their patterns.",
        [("", "paper"), ("", "wax crayons with the wrappers peeled off"), ("1", "bag for leaves")],
        ["Collect leaves of different shapes and sizes.",
         "Put a leaf under the paper, veiny side up, and rub over it with the side of a crayon.",
         "Hold paper against a tree trunk and rub to see the bark pattern.",
         "Label each rubbing with the tree it came from if you can.",
         "Make a collage or a 'tree ID' book."],
    ),
    _item(
        "outdoor", "out-pooh-sticks", "Stick boat races", "⛵", LITTLE, 40, "easy", 5, "2 or more",
        "Build little boats from sticks and leaves and race them down a stream, or play Pooh sticks off a bridge.",
        [("", "sticks, leaves and string or elastic bands")],
        [("Choose a safe, shallow stream or a bridge with railings, and stay close.", G),
         "Tie a few sticks together to make a raft, with a leaf as the sail.",
         "Drop the boats in at the same time upstream.",
         "Run along the bank to see whose wins.",
         "Pooh sticks: drop sticks off the upstream side of a bridge and see whose comes out first."],
        "Try different designs: which floats best and goes fastest?",
    ),
    _item(
        "outdoor", "out-cloud-spotting", "Cloud spotting", "☁️", LITTLE, 20, "easy", 5, "1 or more",
        "Lie back and find shapes in the clouds, then learn the names of the main cloud types.",
        [("1", "blanket"), ("", "paper and pencils")],
        ["Lie on a blanket and look up.",
         "What shapes can you see? Draw your favourite.",
         "Fluffy cotton-wool clouds are cumulus, thin wispy ones are cirrus, and grey sheets are stratus.",
         "Can you guess if it will rain later?",
         "Check again in an hour: how have they changed?"],
        "Never look straight at the sun.",
    ),
    _item(
        "outdoor", "out-bird-feeder", "Pine cone bird feeder", "🐦", LITTLE, 30, "easy", 5, "1 or more",
        "Make a bird feeder from a pine cone, hang it up and see who comes to visit.",
        [("1", "large pine cone"), ("", "lard or vegetable suet, softened"), ("", "bird seed"), ("", "string")],
        ["Tie string tightly round the top of the pine cone.",
         "Spread the soft lard into the gaps with a spoon.",
         "Roll it in bird seed until it's covered.",
         "Hang it from a branch you can see from a window.",
         "Keep a tally of which birds visit over a week."],
        "Avoid peanut butter or cooking fat from the roasting tin: plain lard or suet is safest for birds.",
    ),
    # ---------- ages 8+ ----------
    _item(
        "outdoor", "out-den-building", "Den building", "🛖", JUNIOR, 90, "medium", 8, "2 or more",
        "Build a shelter from branches and a tarp that's big enough to sit in, and test if it keeps you dry.",
        [("", "fallen branches"), ("1", "tarp or old sheet"), ("", "string or rope"), ("", "pegs")],
        ["Find a spot with a strong low branch or two trees close together.",
         "Tie a long branch between them as a ridge pole.",
         "Lean more branches against it on one or both sides.",
         "Cover with the tarp or pile on leaves and ferns.",
         "Water test: pour a cup of water on top. Does it stay dry inside?"],
        "Only use fallen wood, and take the den down afterwards so the area stays wild.",
    ),
    _item(
        "outdoor", "out-treasure-trail", "Map and compass treasure trail", "🧭", JUNIOR, 60, "medium", 8, "1 or more",
        "Follow compass directions and paces from clue to clue to find hidden treasure.",
        [("1", "compass (a phone compass works)"), ("", "clue cards"), ("1", "small treasure")],
        [("Hide the treasure and write clues like 'Walk 20 paces north, then 10 east'.", G),
         "Learn to hold the compass flat and turn until the needle points to N.",
         "Count your paces carefully as you walk.",
         "Find each clue card and follow the next direction.",
         "Swap: now you hide it and write the clues for someone else."],
    ),
    _item(
        "outdoor", "out-rock-pooling", "Rock pooling", "🦀", JUNIOR, 60, "medium", 6, "1 or more",
        "Explore the pools left by the tide and discover crabs, anemones and tiny fish.",
        [("1", "bucket"), ("1", "small net"), ("", "wellies or water shoes"), ("", "tide times")],
        [("Check the tide times and go as the tide goes out. Stay together and watch the sea.", G),
         "Walk carefully: rocks with seaweed are very slippery.",
         "Look under seaweed and in the corners of pools.",
         "Pop finds into a bucket of sea water for a close look.",
         "Put everything back where you found it, gently."],
        "Carry crabs from behind, at the sides of the shell, so they can't pinch.",
    ),
    _item(
        "outdoor", "out-pond-dipping", "Pond dipping", "🐸", JUNIOR, 45, "easy", 6, "1 or more",
        "Sweep a net through a pond and see what lives under the water.",
        [("1", "net"), ("1", "white tray or tub"), ("1", "magnifying glass"), ("", "ID sheet")],
        [("Choose a pond with a safe edge, and kneel rather than stand.", G),
         "Fill the tray with pond water.",
         "Sweep the net slowly in a figure of eight, then tip it into the tray.",
         "Look for water boatmen, snails, tadpoles and dragonfly nymphs.",
         "Return everything gently to the pond and wash hands afterwards."],
    ),
    _item(
        "outdoor", "out-grow-sunflowers", "Sunflower race", "🌻", JUNIOR, 30, "easy", 5, "1 or more",
        "Plant sunflower seeds, measure them each week and see whose grows tallest.",
        [("", "sunflower seeds"), ("", "pots and compost"), ("1", "tape measure"), ("1", "growth chart")],
        ["Plant a seed in each pot, 2 cm deep, and water it.",
         "Keep them somewhere sunny and water when the soil is dry.",
         "Plant them outside against a fence when they're about 20 cm tall.",
         "Measure every week and plot the heights on a chart.",
         "At the end of summer, collect the seeds for next year or for the birds."],
        "Best started in April or May.",
    ),
    _item(
        "outdoor", "out-stargazing", "Stargazing", "✨", JUNIOR, 45, "easy", 7, "1 or more",
        "Wrap up warm on a clear night and find the Plough, the North Star and the Moon's craters.",
        [("", "warm clothes and a blanket"), ("", "a red torch (or torch with red cellophane)"),
         ("", "binoculars if you have them"), ("", "a free star map app")],
        [("Pick a clear night and somewhere away from street lights.", G),
         "Give your eyes 15 minutes to get used to the dark.",
         "Find the Plough: seven stars shaped like a saucepan.",
         "Follow the two stars at the end of the pan upwards to the North Star.",
         "Look at the Moon with binoculars to see its craters."],
    ),
    # ---------- ages 11+ ----------
    _item(
        "outdoor", "out-orienteering", "Orienteering with a real map", "🗺️", TEEN, 120, "tricky", 11, "1 or more",
        "Plan and follow a route with an Ordnance Survey map, using grid references and contour lines.",
        [("1", "OS Explorer map of your area"), ("1", "compass"), ("", "water and snacks")],
        ["Learn the map key: footpaths, woods, water, and contour lines for hills.",
         "Write down a six-figure grid reference for your start and finish.",
         "Plan a 3 to 5 km route and estimate how long it will take.",
         ("Walk it together, with the teen navigating and the grown-up checking.", G),
         "Afterwards, compare your time with your estimate."],
        "Many parks have permanent orienteering courses you can download for free.",
    ),
    _item(
        "outdoor", "out-geocaching", "Geocaching", "📍", TEEN, 90, "medium", 10, "1 or more",
        "Use GPS to find hidden 'caches' in your area, log your find and swap a small trinket.",
        [("1", "phone with a geocaching app"), ("", "a small trinket to swap"), ("1", "pen")],
        [("Set up the app together and agree on safe areas to search.", G),
         "Choose an easy cache near you to start.",
         "Follow the GPS to the area, then search carefully for the hidden container.",
         "Sign the logbook, swap a trinket if you like, and put it back exactly as you found it.",
         "Log the find in the app."],
    ),
    _item(
        "outdoor", "out-bushcraft-fire", "Bushcraft: safe campfire", "🔥", TEEN, 90, "tricky", 12, "2 or more",
        "Learn to lay, light and put out a small fire safely, then toast marshmallows.",
        [("", "a fire pit or bowl"), ("", "tinder (cotton wool with a little petroleum jelly)"),
         ("", "kindling and dry sticks"), ("", "flint and steel or matches"), ("1", "bucket of water")],
        [("Only light fires where it's allowed, in a fire pit, with water ready. Supervise throughout.", G),
         "Gather tinder, pencil-thin kindling and thumb-thick sticks before you start.",
         "Build a small teepee of kindling over the tinder.",
         ("Light the tinder, then feed the fire slowly with bigger sticks.", G),
         "Put it out properly: drown it, stir it, and drown it again until it's cold to touch."],
        "Leave no trace: when you're done the ground should look as if no one was there.",
    ),
    _item(
        "outdoor", "out-bird-survey", "Citizen science bird survey", "🦉", TEEN, 60, "easy", 8, "1 or more",
        "Count the birds in your garden or park for an hour and send the results to real scientists.",
        [("", "binoculars (optional)"), ("", "a bird ID sheet or app"), ("", "tally sheet")],
        ["Pick an hour and a spot where you can see plenty of sky and trees.",
         "Count the most of each species you see at one time (not the total, to avoid counting twice).",
         "Use the ID sheet for tricky ones.",
         "Enter your results online: the RSPB Big Garden Birdwatch runs every January.",
         "Compare with last year's national results."],
    ),
    _item(
        "outdoor", "out-nature-photography", "Nature photography challenge", "📸", TEEN, 60, "medium", 10, "1 or more",
        "Take photos for a list of themes like 'texture', 'reflection' and 'tiny', then make a gallery.",
        [("1", "phone or camera")],
        ["Pick 8 themes: texture, reflection, tiny, pattern, light, movement, colour, something old.",
         "Explore and take a few shots for each.",
         "Try different angles: get low to the ground, or shoot from above.",
         "Choose your best one for each theme.",
         "Share them as a gallery or print them for a Moment."],
    ),
    _item(
        "outdoor", "out-plan-a-hike", "Plan and lead a hike", "🥾", TEEN, 240, "tricky", 13, "2 or more",
        "Teens plan a whole day walk: route, timings, kit list and weather, then lead the family.",
        [("1", "map"), ("", "weather forecast"), ("", "kit list"), ("", "packed lunch")],
        ["Choose a route and check its length and hills.",
         "Work out timings using about 4 km an hour plus extra for hills and breaks.",
         "Write the kit list and check the weather the day before.",
         "Tell someone at home your route and when you'll be back.",
         ("On the day, the teen leads while a grown-up keeps an eye on safety.", G)],
        "Great evidence for Duke of Edinburgh or John Muir awards.",
    ),
]
