import type { TopicPack } from "@/lib/topics";

/** All about the Romans: the Roman Empire and Roman Britain, for ages 7 to 11. */
export const romans: TopicPack = {
  slug: "romans",
  title: "All about the Romans",
  short: "Romans",
  subject: "History",
  ages: "7 to 11",
  length: "6 lessons, about an hour each",
  color: "#B5523B",
  emoji: "🏛️",
  summary: "Rome, the invasion of Britain, Boudica, the walls and Roman life",
  intro:
    "Who the Romans were, how they came to Britain, who fought back, why they built walls across the country, and what they left behind. Six ready-to-teach lessons with everything you need to know first, so you don't have to research anything yourself.",
  curriculum: {
    england: "Key Stage 2 history: the Roman Empire and its impact on Britain, including Julius Caesar, Claudius's invasion, Boudica's revolt, Hadrian's Wall and how Britain became Roman.",
    scotland:
      "Social studies, second level (people, past events and societies): comparing a society in the past with our own, and using evidence to find out about the past. The Antonine Wall lesson brings in Scotland's own Roman story.",
  },

  background: [
    {
      heading: "The big picture",
      text: [
        "Rome began as a small town in Italy. Over hundreds of years its army conquered the lands around the Mediterranean Sea, until the Roman Empire stretched from Britain to Egypt and the Middle East. It was ruled by an emperor.",
        "Julius Caesar came to Britain twice, in 55 BC and 54 BC, but didn't stay. The real invasion came in AD 43, under Emperor Claudius. For almost 400 years after that, most of what is now England and Wales was a Roman province called Britannia. The Romans never conquered most of Scotland, which they called Caledonia.",
        "By around AD 410 the Roman army had left to defend other parts of the empire, which was under attack, and Britain was told to look after itself.",
      ],
    },
    {
      heading: "Who's who",
      text: [
        "Julius Caesar: a Roman general who came to Britain twice but went home again. The month July is named after him.",
        "Claudius: the emperor who invaded in AD 43. He came to Britain himself for a few weeks to see the capture of Camulodunum (Colchester).",
        "Caratacus: a British leader who fought the Romans for years. He was captured in AD 51 and taken to Rome, where the Roman writer Tacitus says his brave speech made Claudius spare his life.",
        "Boudica: queen of the Iceni tribe in East Anglia, who led a huge revolt in AD 60 or 61.",
        "Hadrian: the emperor who ordered the wall across northern England, begun in AD 122.",
        "Antoninus Pius: the next emperor, who built a second wall further north, across central Scotland.",
      ],
    },
    {
      heading: "How we know",
      text: [
        "The Britons wrote very little down, so most of the written story comes from Roman writers such as Tacitus and Cassius Dio, who were not there and wrote from Rome's side. The rest comes from archaeology: forts, roads, coins, mosaics, burnt layers of ash under towns Boudica destroyed, and the Vindolanda tablets, letters written on thin slivers of wood near Hadrian's Wall. It's worth asking 'how do we know?' often. It's one of the most important skills in history.",
      ],
    },
    {
      heading: "The tricky bits",
      text: [
        "The Roman world was violent and depended on enslaved people, and Boudica's story starts with her family being treated cruelly. You don't need to hide this, but you can choose how much detail to give. 'The Romans treated Boudica and her daughters very cruelly' is enough for most children. If slavery comes up, it's fine to say plainly that it was wrong, and that many people in the empire were treated as property.",
        "Gladiators come up a lot. They were real and the fights were dangerous, but not every fight ended in death, as gladiators were expensive to train.",
      ],
    },
    {
      heading: "How to teach it at home",
      text: [
        "Do one lesson a week over a half term, or two a week for three weeks. Each lesson starts with the story (read the 'Tell the story' part first, then tell it in your own words), then something hands-on, then a few questions to talk about. Keep a topic book where your child sticks in what they make and write.",
        "If you can, visit a Roman site or museum during the topic: seeing a real Roman wall or mosaic makes everything stick. The list of places is near the bottom of this page.",
        "Finish with the Big Romans Quiz. Print the knowledge organiser for your child's topic book at the start, so they can look back at it as you go.",
      ],
    },
  ],

  facts: [
    "The Romans came from Rome, a city in Italy.",
    "The Roman Empire was ruled by an emperor, and at its biggest it stretched from Britain to Egypt.",
    "Julius Caesar came to Britain in 55 BC and 54 BC, but didn't stay.",
    "In AD 43 Emperor Claudius invaded Britain with about 40,000 soldiers.",
    "The Romans called Britain 'Britannia'.",
    "In AD 60 or 61 Queen Boudica of the Iceni led a revolt and burned three Roman towns, including London.",
    "Hadrian's Wall, begun in AD 122, ran about 73 miles across the north of England.",
    "The Antonine Wall, begun in AD 142, ran across central Scotland, between the Forth and the Clyde.",
    "The Romans spoke Latin and wrote numbers with letters: I, V, X, L, C, D and M.",
    "They built long straight roads, towns, public baths, and villas with mosaic floors.",
    "The Romans ruled much of Britain for nearly 400 years, until about AD 410.",
  ],

  timeline: [
    { when: "753 BC", what: "Rome is founded, according to the legend of Romulus and Remus" },
    { when: "55 and 54 BC", what: "Julius Caesar comes to Britain twice, then leaves" },
    { when: "AD 43", what: "Emperor Claudius invades Britain" },
    { when: "AD 51", what: "The British leader Caratacus is captured" },
    { when: "AD 60 or 61", what: "Boudica's revolt" },
    { when: "AD 79", what: "Mount Vesuvius erupts and buries the Roman town of Pompeii in Italy" },
    { when: "About AD 100", what: "Claudia Severa sends a birthday party invitation to her friend at Vindolanda" },
    { when: "AD 122", what: "Work begins on Hadrian's Wall" },
    { when: "AD 142", what: "Work begins on the Antonine Wall in Scotland" },
    { when: "About AD 410", what: "Roman rule in Britain comes to an end" },
  ],

  words: [
    { word: "empire", meaning: "lots of lands and peoples ruled by one ruler or country" },
    { word: "emperor", meaning: "the ruler of the Roman Empire" },
    { word: "invade", meaning: "to go into another country with an army to take it over" },
    { word: "province", meaning: "a part of the empire, like Britannia" },
    { word: "legion", meaning: "a group of about 5,000 Roman soldiers" },
    { word: "legionary", meaning: "a Roman soldier in a legion" },
    { word: "centurion", meaning: "the officer in charge of a century, about 80 soldiers" },
    { word: "tribe", meaning: "a group of families with the same leader, like the Iceni" },
    { word: "revolt", meaning: "when people fight back against the people ruling them" },
    { word: "Celts", meaning: "the name often used for the people living in Britain before the Romans" },
    { word: "roundhouse", meaning: "a round home with a thatched roof, built by Iron Age Britons" },
    { word: "fort", meaning: "a strong, walled camp for soldiers" },
    { word: "villa", meaning: "a large Roman house in the countryside" },
    { word: "mosaic", meaning: "a picture made from lots of tiny pieces of stone or tile" },
    { word: "hypocaust", meaning: "Roman underfloor heating, using hot air from a fire" },
    { word: "forum", meaning: "the main square and market place in a Roman town" },
    { word: "Latin", meaning: "the language the Romans spoke and wrote" },
    { word: "BC and AD", meaning: "BC years count down to the year 1, and AD years count up from it" },
    { word: "source", meaning: "anything that tells us about the past, like a letter, a coin or a ruin" },
  ],

  myths: [
    { myth: "Britain was wild and empty before the Romans came.", truth: "Iron Age Britons farmed, traded with Europe, made their own coins and beautiful metalwork, and lived in villages and hill forts." },
    { myth: "The Romans conquered all of Britain.", truth: "They never conquered most of Scotland. That's why they built Hadrian's Wall and the Antonine Wall." },
    { myth: "All the Romans in Britain came from Rome.", truth: "Soldiers and their families came from all over the empire, from places that are now Belgium, Spain, Syria and North Africa. And many Britons became Roman too." },
    { myth: "Gladiator fights always ended in death.", truth: "Gladiators were expensive to train, so many fights ended when one gave up. They were still very dangerous." },
    { myth: "Roman statues were plain white marble.", truth: "Many were painted in bright colours. The paint has worn off over 2,000 years." },
    { myth: "The Romans invented roads.", truth: "Britain already had tracks and paths. The Romans built a network of long, straight, paved roads, and some of our roads still follow them." },
  ],

  lessons: [
    {
      title: "Who were the Romans?",
      emoji: "🗺️",
      minutes: 60,
      aim: "Know that the Romans came from Rome in Italy, built a huge empire, and where they fit on a timeline.",
      need: ["A map of Europe or a globe", "String and pegs, or a long strip of paper", "Some cards or paper and pens"],
      say: [
        "Nearly 3,000 years ago, Rome was a small town in Italy. The Romans told a legend that it was started in 753 BC by twin brothers called Romulus and Remus, who were looked after by a wolf when they were babies.",
        "Rome grew and grew. Its army conquered the lands around it until the Roman Empire stretched all the way from Britain to Egypt and the Middle East, and tens of millions of people lived in it.",
        "An empire is lots of lands ruled by one ruler or country. The ruler of the Roman Empire was called the emperor.",
        "We count years from when Jesus was thought to have been born. BC years count down towards that year, and AD years count up from it. So 55 BC is a long time before AD 43.",
      ],
      doIt: [
        "Find Rome and Italy on the map, then find Britain. Trace the way a Roman soldier would have travelled to get here.",
        "Make a washing-line timeline. Write each date on a card and peg it up in order: 753 BC Rome begins, 55 BC Julius Caesar comes, AD 43 the invasion, AD 60 Boudica, AD 122 Hadrian's Wall, AD 410 the Romans leave. Put 'Today' at the far end, with the year your child was born.",
        "Talk about how long 400 years is. With about 25 years between a parent and child, that's about 16 generations, so it's like a grandparent's grandparent's grandparent... going back 16 times.",
      ],
      ask: ["Where did the Romans come from?", "What is an empire?", "Which was longer ago, 55 BC or AD 43? How do you know?", "Why do you think BC numbers count down?"],
      younger: "Use just four cards with a picture on each: Rome begins, the Romans arrive, the wall is built, the Romans leave.",
      older: "Make the timeline to scale: 10 centimetres for every 100 years. Where are the biggest gaps?",
    },
    {
      title: "The Romans come to Britain",
      emoji: "⛵",
      minutes: 60,
      aim: "Know what Britain was like before the Romans, and how and why the Romans invaded in AD 43.",
      need: ["Paper folded into two columns", "For the model: a paper cup or card tube, card, glue, and straw, wool or brown tissue paper"],
      say: [
        "Before the Romans came, Britain was in the Iron Age. People lived in tribes, each with its own leader. They farmed, kept animals, made iron tools and beautiful jewellery, and lived in round houses with thatched roofs. We often call them Celts or Britons.",
        "In 55 BC a Roman general called Julius Caesar sailed across the sea to Britain. He fought some of the tribes, but he went home. He came back the next year, in 54 BC, and went home again.",
        "Almost 100 years later, in AD 43, Emperor Claudius sent about 40,000 soldiers. They landed in Kent and fought their way across the south. Claudius came himself to see them capture Camulodunum, which we now call Colchester. It became the first capital of the new Roman province of Britannia.",
        "Why did the Romans want Britain? It had metals like tin, lead, silver and gold, and good farmland for growing grain. And conquering a new land made an emperor look strong and powerful back in Rome.",
        "Some tribes fought the Romans. Others made deals with them and became their friends.",
      ],
      doIt: [
        "Make a 'Britons and Romans' chart with two columns. Compare their homes, clothes, weapons, writing and towns. Keep it in the topic book: you'll add to it in later lessons.",
        "Make a model roundhouse: a paper cup or card tube for the walls, and a cone of card for the roof, covered in straw, wool or scrunched brown tissue paper for thatch.",
      ],
      ask: ["Why did the Romans want Britain?", "Why do you think Julius Caesar didn't stay?", "If you were a tribe's leader, would you fight the Romans or make friends with them? Why?"],
      younger: "Just make the roundhouse, and talk about what it would be like to live in one: where would you cook, and where would you sleep?",
      older: "Most of what we know about the invasion was written by Romans. Why might that be a problem? What might a Briton have said instead?",
    },
    {
      title: "The Roman army",
      emoji: "🛡️",
      minutes: 60,
      aim: "Know how the Roman army was organised and equipped, and why it was so hard to beat.",
      need: ["A big piece of cardboard", "Paint or felt pens in red and yellow", "Somewhere to march, inside or out"],
      say: [
        "The Roman army was made of full-time soldiers who trained every day. A legionary signed up for about 25 years.",
        "Soldiers were put into groups. A legion had about 5,000 soldiers. It was split into centuries of 80 soldiers, each led by an officer called a centurion. ('Centum' means 100 in Latin, but a century had 80!)",
        "Each soldier had a metal helmet, armour made from metal strips, a big curved shield called a scutum, a short sword called a gladius, a throwing spear called a pilum, and sandals with iron nails in the soles. On the march they also carried tools, food and cooking pots.",
        "In battle they could lock their shields together over their heads and around the sides, like the shell of a tortoise. They called this the testudo, which means tortoise.",
        "Soldiers didn't only fight. They built forts, bridges and long straight roads, so the army could move quickly from one place to another.",
      ],
      doIt: [
        "Make a Roman shield: cut a big rectangle from the cardboard, bend it gently so it curves, and paint it red with yellow lightning bolts or wings.",
        "March like a legionary. Romans counted their marching as 'sinister, dexter', which is Latin for 'left, right'.",
        "A Roman mile was 1,000 paces ('mille passus'), and a pace was two steps. Count out 100 paces in the park or garden, then work out how far 1,000 would be.",
      ],
      ask: ["Why was the Roman army so hard to beat?", "What do you think was the hardest part of being a Roman soldier?", "Why do you think soldiers built roads as well as fighting?"],
      younger: "Decorate a paper plate as a shield and practise marching while counting to ten.",
      older: "Write a diary for one day in the life of a legionary. What do they do, eat and worry about?",
    },
    {
      title: "Boudica fights back",
      emoji: "⚔️",
      minutes: 60,
      aim: "Know the story of Boudica's revolt, and think about who tells the story and why that matters.",
      need: ["Paper and pens for a newspaper front page", "A scarf or cloak for dressing up (optional)"],
      say: [
        "The Iceni were a tribe living in what is now Norfolk. Their king, Prasutagus, had made friends with the Romans. When he died, around AD 60, he left half of his kingdom to the emperor and half to his daughters, hoping that would keep his family safe.",
        "It didn't. The Romans took everything, and they treated his wife, Queen Boudica, and their daughters very cruelly.",
        "Boudica was furious. She led the Iceni and their neighbours, the Trinovantes, in a huge revolt. They destroyed three Roman towns: Camulodunum (Colchester), Londinium (London) and Verulamium (St Albans). Archaeologists still find a red and black layer of burnt ground under these towns from the fires.",
        "The Roman governor, Suetonius Paulinus, was away fighting in Wales. He marched his army back and beat Boudica's much bigger army in a battle. Nobody knows exactly where it was. Boudica died soon afterwards.",
        "Everything we know about Boudica was written by two Roman writers, Tacitus and Cassius Dio, years later. None of the Iceni wrote down their side of the story.",
      ],
      doIt: [
        "Hot-seating: your child is Boudica, and you ask the questions. Why are you so angry? What do you want? Then swap, and your child is a Roman soldier in London.",
        "Write the front page of 'The Britannia Times' on the day Londinium burns. Give it a headline, a picture, and a report. Is the newspaper on the Romans' side or the Britons' side?",
      ],
      ask: ["Was Boudica a hero or a rebel? Does it depend on who you ask?", "Why might a Roman writer tell the story differently from an Iceni person?", "There's a big statue of Boudica in her chariot next to the Houses of Parliament in London. Why do you think people made it, 1,800 years later?"],
      younger: "Tell the story in four pictures, like a comic strip: the king dies, the Romans are cruel, Boudica fights back, the big battle.",
      older: "Cassius Dio described Boudica as very tall and frightening, with long red-gold hair, a harsh voice and a big gold necklace. He never met her. Why do you think he described her like that?",
    },
    {
      title: "Walls at the edge of the empire",
      emoji: "🧱",
      minutes: 60,
      aim: "Know why Hadrian's Wall and the Antonine Wall were built, and what life was like at a fort.",
      need: ["Building blocks, Lego or small boxes", "A map of Britain", "A strip of card and a pen for the letter"],
      say: [
        "The Romans never conquered most of the land we now call Scotland. They called it Caledonia, and the tribes there often raided the Roman lands to the south.",
        "Emperor Hadrian visited Britain in AD 122 and ordered a wall to be built from coast to coast, from the River Tyne near Newcastle to the Solway Firth in the west. It was about 73 miles long. There were big forts along it, a small fort called a milecastle every Roman mile, and lookout towers in between.",
        "The wall had gates. It didn't only keep people out: it let the Romans control who came and went, and make traders pay taxes.",
        "About 20 years later, the next emperor, Antoninus Pius, pushed further north and built the Antonine Wall across central Scotland, between the Firth of Forth and the River Clyde. It was made of turf on a stone base, with a deep ditch in front. The army only stayed there for about 20 years before moving back to Hadrian's Wall.",
        "At a fort called Vindolanda, near Hadrian's Wall, archaeologists found hundreds of letters written in ink on thin pieces of wood. One is a birthday party invitation from a woman called Claudia Severa to her friend Sulpicia Lepidina. Others ask for socks, underpants and more beer!",
      ],
      doIt: [
        "Mark Hadrian's Wall and the Antonine Wall on a map of Britain. Which is longer? Which is further north?",
        "Build a stretch of wall with blocks, with a gate and a lookout tower. Play guards: who is allowed through, and what do they have to pay?",
        "Write a Vindolanda letter on a long strip of card: invite a friend to your birthday party, or write home asking for something you need at the fort.",
      ],
      ask: ["Was the wall built to keep people out, or to control who came in?", "If you were a soldier from a warm country, what would you miss at Hadrian's Wall?", "Why do you think the Antonine Wall didn't last as long?"],
      younger: "Build the wall and the gate, then play guards together.",
      older: "Hadrian's Wall is about 73 miles. If you walked 12 miles a day, how many days would it take to walk it? Many people walk it today on the Hadrian's Wall Path.",
    },
    {
      title: "Roman life and what they left behind",
      emoji: "🏛️",
      minutes: 60,
      aim: "Know about Roman towns, homes, baths and gods, and spot things from Roman times that are still around today.",
      need: ["Coloured paper cut into small squares", "Glue and a sheet of card", "A pencil"],
      say: [
        "The Romans built towns with straight streets, a forum (a market square), temples, public baths, and sometimes an amphitheatre for shows. Many of our towns and cities began as Roman ones: London was Londinium, York was Eboracum, Chester was Deva, Bath was Aquae Sulis and Lincoln was Lindum.",
        "Town names ending in -chester, -caster or -cester, like Manchester, Lancaster and Gloucester, usually come from the Latin word 'castra', meaning a camp or fort.",
        "Rich Romans lived in villas with mosaic floors, pictures made from thousands of tiny squares of stone called tesserae. Some had underfloor heating called a hypocaust: hot air from a fire flowed under the floor.",
        "At the baths, people went from a warm room to a hot room, then into a cold pool. Instead of soap, they rubbed oil on their skin and scraped it off with a curved metal tool called a strigil.",
        "The Romans believed in many gods: Jupiter the king of the gods, Mars the god of war, Venus the goddess of love, Neptune the god of the sea, and Minerva the goddess of wisdom. Later, the empire became Christian.",
        "Lots of Roman things are still around us: roads that follow Roman ones, Latin words in English, Roman numerals on clocks, and the months July and August, named after Julius Caesar and the Emperor Augustus.",
      ],
      doIt: [
        "Make a mosaic: draw a simple design on card, such as a dolphin, a flower or your first initial, then fill it with small squares of coloured paper, leaving tiny gaps between them.",
        "Be a Latin detective. Which English words come from these Latin ones? aqua (water), portus (harbour), annus (year), centum (hundred), manus (hand), video (I see), audio (I hear).",
        "Go on a Roman numerals hunt around the house and outside: clocks, watches, the end of film credits, the names of kings and queens, and old buildings.",
      ],
      ask: ["Which Roman thing do you think was the most useful?", "Would you have liked going to a Roman bath? Why or why not?", "Did the Romans make life better or worse for the people of Britain? Who do you think it was better for?"],
      younger: "Make a mosaic with bigger squares and a simple shape like a sun or a fish.",
      older: "Hold a debate: 'The Romans were good for Britain.' Find three reasons for and three against, then decide what you really think.",
    },
  ],

  activities: [
    {
      emoji: "🍯",
      title: "Bake Roman libum",
      kind: "Cooking",
      text: "A honey cheese bread from a recipe written down by a Roman called Cato more than 2,000 years ago. A grown-up does the oven.",
      steps: [
        "Heat the oven to 200°C (180°C fan). Put a few bay leaves on a lined baking tray, if you have them.",
        "Mix 250g ricotta and 1 beaten egg, then stir in 125g plain flour to make a soft dough.",
        "Shape it into 4 small round buns and put them on the bay leaves.",
        "Bake for about 30 minutes, until golden. Drizzle with honey while still warm.",
      ],
    },
    {
      emoji: "🛣️",
      title: "Build a Roman road",
      kind: "Outdoors",
      text: "Roman roads were built in layers, with a curved top so the rain ran off into ditches at the sides.",
      steps: [
        "In a seed tray, a washing-up bowl or a corner of the garden, dig a shallow trench.",
        "Put in a layer of big stones, then smaller stones or gravel, then sand.",
        "Finish with flat stones on top, higher in the middle than at the edges.",
        "Pour a jug of water over it. Where does the water go?",
      ],
    },
    {
      emoji: "⭕",
      title: "Play terni lapilli",
      kind: "Game",
      text: "Roman noughts and crosses. Draw a 3 by 3 grid. Each player has only three counters. Take turns to put them down, and once all six are on the board, take turns to slide one of yours to an empty space next to it. The first to get three in a row wins.",
    },
    {
      emoji: "✍️",
      title: "Make a wax tablet",
      kind: "Craft",
      text: "Roman children practised writing on wooden tablets covered in wax, using a pointed stick called a stylus. Press plasticine or play dough flat into the lid of a box, and write on it with a lolly stick. Smooth it over to start again.",
    },
    {
      emoji: "🪙",
      title: "Design a Roman coin",
      kind: "Craft",
      text: "Roman coins showed the emperor's head and his name. Draw round a mug on card and design a coin with your own head on it, as emperor. Cover it with foil and press the design through with a blunt pencil.",
    },
    {
      emoji: "🔢",
      title: "Roman numerals",
      kind: "Maths",
      text: "I is 1, V is 5, X is 10, L is 50 and C is 100. A smaller letter before a bigger one means take it away, so IV is 4 and IX is 9. Try the Roman numerals sheet below, then write today's date in Roman numerals.",
    },
  ],

  books: [
    { title: "Roman Diary: The Journal of Iliona, a Young Slave", by: "Richard Platt", note: "A girl's diary of life in a Roman household. A good read-aloud for 8 and up." },
    { title: "Rotten Romans (Horrible Histories)", by: "Terry Deary", note: "Funny and gruesome. Children often read it on their own." },
    { title: "Romans on the Rampage", by: "Jeremy Strong", note: "A short, silly story for confident readers of 7 and up." },
    { title: "You Wouldn't Want to Be a Roman Soldier!", by: "David Stewart", note: "Picture-packed and good for the army lesson." },
    { title: "Escape from Pompeii", by: "Christina Balit", note: "A beautiful picture book about the eruption of Vesuvius." },
    { title: "The Thieves of Ostia (The Roman Mysteries)", by: "Caroline Lawrence", note: "The first of a mystery series set in Roman times, for 9 and up." },
    { title: "The Eagle of the Ninth", by: "Rosemary Sutcliff", note: "A classic adventure set around Hadrian's Wall, for strong readers of 10 and up." },
  ],

  online: [
    { title: "Roman Britain", by: "English Heritage", note: "Short articles on the invasion, Hadrian, villas, baths and roads.", url: "https://www.english-heritage.org.uk/learn/story-of-england/romans/" },
    { title: "The Vindolanda tablets", by: "British Museum", note: "See the real birthday invitation and other letters from the fort.", url: "https://www.britishmuseum.org/collection/galleries/roman-britain/vindolanda-tablets" },
    { title: "The Antonine Wall", note: "Maps, pictures and the story of Scotland's Roman wall.", url: "https://www.antoninewall.org/" },
    { title: "BBC Bitesize", by: "BBC", note: "Search for 'Romans' to find short videos and quizzes for KS2 and second level.", url: "https://www.bbc.co.uk/bitesize" },
  ],

  visits: [
    { title: "Hadrian's Wall", by: "Northumberland and Cumbria", note: "Housesteads and Birdoswald forts are good with children.", url: "https://www.english-heritage.org.uk/visit/places/hadrians-wall/" },
    { title: "Vindolanda and the Roman Army Museum", by: "Northumberland", note: "Where the writing tablets were found. Digs carry on every summer.", url: "https://www.vindolanda.com/" },
    { title: "The Antonine Wall", by: "Central Scotland", note: "Rough Castle and Bar Hill have the best bits to walk along.", url: "https://www.antoninewall.org/" },
    { title: "The Roman Baths", by: "Bath", note: "The steaming Great Bath and the temple of Sulis Minerva.", url: "https://www.romanbaths.co.uk/" },
    { title: "National Roman Legion Museum", by: "Caerleon, near Newport", note: "Free, with a fort, barracks and an amphitheatre nearby.", url: "https://museum.wales/roman/" },
    { title: "Fishbourne Roman Palace", by: "near Chichester, West Sussex", note: "The biggest Roman house found in Britain, with amazing mosaic floors." },
    { title: "Colchester Castle", by: "Colchester", note: "The castle stands on top of the Roman temple to Claudius that Boudica destroyed." },
    { title: "Verulamium Museum", by: "St Albans", note: "Mosaics, a hypocaust and the remains of the Roman town." },
  ],

  sheets: [
    {
      slug: "big-romans-quiz",
      title: "The Big Romans Quiz",
      intro: "Ten questions about everything in the topic. Do it at the end, or try it at the start too and see how much you've learned.",
      questions: [
        { type: "choice", q: "Which city did the Romans come from?", options: ["Athens", "Rome", "London"], answer: 1, why: "Rome is in Italy." },
        { type: "choice", q: "What did the Romans call Britain?", options: ["Caledonia", "Britannia", "Londinium"], answer: 1, why: "Caledonia was what they called Scotland, and Londinium was London." },
        {
          type: "order",
          q: "Put these in order. Tap the oldest first.",
          items: ["Julius Caesar comes to Britain", "Claudius invades", "Boudica's revolt", "Hadrian's Wall is begun"],
        },
        { type: "type", q: "In which year did Emperor Claudius invade Britain? AD...", answer: "43" },
        { type: "choice", q: "Who was Boudica?", options: ["A Roman emperor", "Queen of the Iceni tribe", "A gladiator"], answer: 1 },
        {
          type: "match",
          q: "Match each Roman name to the place we call it today.",
          pairs: [["Londinium", "London"], ["Eboracum", "York"], ["Aquae Sulis", "Bath"], ["Deva", "Chester"]],
        },
        { type: "choice", q: "About how many soldiers were in a Roman century?", options: ["8", "80", "800"], answer: 1, why: "Even though 'centum' means 100!" },
        {
          type: "pick",
          q: "Which of these did the Romans build in Britain? There is more than one.",
          options: ["Straight roads", "Stonehenge", "Hadrian's Wall", "Public baths", "The Tower of London"],
          answers: [0, 2, 3],
          why: "Stonehenge is thousands of years older, and the Tower of London was built by the Normans.",
        },
        {
          type: "gap",
          q: "Fill the gaps.",
          text: "Rich Romans lived in a ___ with ___ floors made from tiny squares of stone.",
          bank: ["roundhouse", "villa", "carpet", "mosaic"],
          answers: ["villa", "mosaic"],
        },
        {
          type: "choice",
          q: "Why did the Romans build Hadrian's Wall?",
          options: ["To keep out the sea", "To control the border with the tribes in the north", "To hold up a road"],
          answer: 1,
        },
      ],
    },
    {
      slug: "roman-numerals",
      title: "Roman numerals",
      intro: "I is 1, V is 5, X is 10, L is 50 and C is 100. Add the letters up. But if a smaller one comes before a bigger one, take it away: IV is 5 take away 1, which is 4.",
      questions: [
        { type: "match", q: "Match each Roman numeral to its number.", pairs: [["I", "1"], ["V", "5"], ["X", "10"], ["L", "50"], ["C", "100"]] },
        { type: "type", q: "What number is III?", answer: "3" },
        { type: "type", q: "What number is VIII?", answer: "8", why: "V is 5, and III is 3 more." },
        { type: "type", q: "What number is XII?", answer: "12" },
        { type: "type", q: "What number is IV?", answer: "4", why: "I comes before V, so take 1 away from 5." },
        { type: "type", q: "What number is IX?", answer: "9", why: "I comes before X, so take 1 away from 10." },
        { type: "type", q: "Write 7 in Roman numerals.", answer: "VII" },
        { type: "type", q: "Write 15 in Roman numerals.", answer: "XV" },
        { type: "choice", q: "Which is bigger?", options: ["XL", "LX"], answer: 1, why: "XL is 50 take away 10, which is 40. LX is 50 add 10, which is 60." },
        { type: "type", q: "Claudius invaded in AD XLIII. What year is that?", answer: "43", why: "XL is 40, and III is 3." },
      ],
    },
  ],
};
